/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Skeleton — Full-width with percentage
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Skeleton/SkeletonFullwidthWithPercentage';
