/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Token — With icon and hidden label
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Token/TokenWithIconAndHiddenLabel';
