/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Dialog — Header With Close Button
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Dialog/DialogHeaderWithCloseButton';
