/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Selector — With Object Items
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Selector/SelectorWithObjectItems';
