/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ToggleButton — Multi-select group
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ToggleButton/ToggleButtonMultiselectGroup';
