/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DropdownMenu — With Icons
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DropdownMenu/DropdownMenuWithIcons';
