/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Table — Auto-generated columns
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Table/TableAutogeneratedColumns';
