/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — With Min Max Constraints
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputWithMinMaxConstraints';
