/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Kbd — Single Shortcut
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Kbd/KbdSingleShortcut';
