/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Slider — Text value display
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Slider/SliderTextValueDisplay';
