/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextArea — Disabled
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextArea/TextAreaDisabled';
