/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Markdown — Streaming Mode
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Markdown/MarkdownStreamingMode';
