/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Card — Color Variant
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Card/CardColorVariant';
