/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Calendar — Single Date
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Calendar/CalendarSingleDate';
