/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Carousel — Basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Carousel/CarouselBasic';
