/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TopNav — In XDSLayout header slot
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TopNav/TopNavInXDSLayoutHeaderSlot';
