/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Stack — Override alignment per item
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Stack/StackOverrideAlignmentPerItem';
