/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Link — Standalone
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Link/LinkStandalone';
