/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Table — Selection plugin
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Table/TableSelectionPlugin';
