/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NavIcon — In Top Navigation
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NavIcon/NavIconInTopNavigation';
