/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Layer — Fixed Mode
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Layer/LayerFixedMode';
