/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Icon — Direct Components
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Icon/IconDirectComponents';
