/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Banner — Simple
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Banner/BannerSimple';
