/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CommandPalette — Static Source
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CommandPalette/CommandPaletteStaticSource';
