/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CheckboxList — With Status
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CheckboxList/CheckboxListWithStatus';
