/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Stack — Sidebar layout
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Stack/StackSidebarLayout';
