/**
 * @file theme command — Discover and apply XDS themes
 *
 * Scans packages/core/src/theme/*Theme.stylex.ts for available themes.
 * Writes xds.config.mjs with the selected theme.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {findCoreDir} from '../utils/paths.mjs';

/**
 * Discover available themes by scanning theme directory.
 * Returns array of {name, exportName} objects.
 */
export function discoverThemes(coreDir) {
  const themeDir = path.join(coreDir, 'src', 'theme');
  if (!fs.existsSync(themeDir)) return [];

  const files = fs.readdirSync(themeDir);
  return files
    .filter(f => f.endsWith('Theme.stylex.ts'))
    .map(f => {
      const exportName = f.replace('.stylex.ts', '');
      const name = exportName.replace('Theme', '');
      return {name, exportName};
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Write xds.config.mjs with the selected theme.
 */
export function writeThemeConfig(targetDir, themeExportName) {
  const configPath = path.join(targetDir, 'xds.config.mjs');
  const content = `/**
 * XDS Configuration
 * Generated by \`xds theme\`
 */
export default {
  theme: '${themeExportName}',
};
`;
  fs.writeFileSync(configPath, content);
  return configPath;
}

export function registerTheme(program) {
  program
    .command('theme [preset]')
    .description('Apply a prebuilt XDS theme')
    .option('--list', 'List available themes')
    .action((preset, options) => {
      const coreDir = findCoreDir(process.cwd());

      if (!coreDir) {
        console.error(
          'Error: Could not find @xds/core package.\n' +
            'Make sure you are inside the XDS monorepo or have @xds/core installed.',
        );
        process.exit(1);
      }

      const themes = discoverThemes(coreDir);

      if (themes.length === 0) {
        console.error('Error: No themes found in packages/core/src/theme/');
        process.exit(1);
      }

      if (options.list || !preset) {
        console.log('\nAvailable themes:\n');
        for (const theme of themes) {
          const label = theme.name === 'default' ? ' (default)' : '';
          console.log(`  ${theme.name}${label} — import { ${theme.exportName} } from '@xds/core/theme'`);
        }
        console.log('\nUsage: xds theme <name>\n');
        return;
      }

      const theme = themes.find(t => t.name === preset);

      if (!theme) {
        console.error(`Error: Unknown theme "${preset}".`);
        console.error(`Available: ${themes.map(t => t.name).join(', ')}`);
        process.exit(1);
      }

      const configPath = writeThemeConfig(process.cwd(), theme.exportName);
      console.log(`\n✓ Wrote ${path.relative(process.cwd(), configPath)}\n`);
      console.log('Add the theme provider to your root layout:\n');
      console.log(`  import { XDSTheme, ${theme.exportName} } from '@xds/core/theme';`);
      console.log('');
      console.log('  <XDSTheme theme={' + theme.exportName + '}>');
      console.log('    {children}');
      console.log('  </XDSTheme>\n');
    });
}
