/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: RadioList — With Descriptions
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/RadioList/RadioListWithDescriptions';
