/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Pagination — Carousel Dots
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Pagination/PaginationCarouselDots';
