/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Slider — With onChangeEnd for committing value
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Slider/SliderWithOnChangeEndForCommittingValue';
