/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Timestamp — Live updating
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Timestamp/TimestampLiveUpdating';
