/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Pagination — Page Number Buttons
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Pagination/PaginationPageNumberButtons';
