/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — With Step For Decimals
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputWithStepForDecimals';
