/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Toolbar — Basic toolbar with start and end actions
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Toolbar/ToolbarBasicToolbarWithStartAndEndActions';
