/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TimeInput — Basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TimeInput/TimeInputBasic';
