/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DateInput — Basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DateInput/DateInputBasic';
