/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Typeahead — Basic typeahead
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Typeahead/TypeaheadBasicTypeahead';
