/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MultiSelector — Badges Trigger Display
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MultiSelector/MultiSelectorBadgesTriggerDisplay';
