/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: StatusDot — Basic status indicators
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/StatusDot/StatusDotBasicStatusIndicators';
