/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Badge — Text Badge
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Badge/BadgeTextBadge';
