/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NavIcon — With Home Icon
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NavIcon/NavIconWithHomeIcon';
