/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Markdown — Nested Heading
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Markdown/MarkdownNestedHeading';
