/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Avatar — Status Dot Sizes
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Avatar/AvatarStatusDotSizes';
