/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Field — Optional
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Field/FieldOptional';
