/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Slider — Disabled
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Slider/SliderDisabled';
