/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TabList — With links
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TabList/TabListWithLinks';
