/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Divider — Full Bleed
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Divider/DividerFullBleed';
