/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: PowerSearch — With Content Search Field Key
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/PowerSearch/PowerSearchWithContentSearchFieldKey';
