/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Timestamp — Date only
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Timestamp/TimestampDateOnly';
