/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Table — Column resize plugin
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Table/TableColumnResizePlugin';
