/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Badge — Status Variants
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Badge/BadgeStatusVariants';
