/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextArea — Error status with message
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextArea/TextAreaErrorStatusWithMessage';
