/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AppShell — Full Bleed With Padded
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AppShell/AppShellFullBleedWithPadded';
