/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Spinner — A11y only (no visible text)
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Spinner/SpinnerA11yOnlyNoVisibleText';
