'use client';

/**
 * @file XDSMediaTheme.tsx
 * @input surface prop ("dark" | "light") + children
 * @output Wrapper div that creates an inverted theming context
 * @position Theme system component; sibling to XDSTheme
 *
 * Provides semantic token overrides for content rendered on a surface
 * with a different luminance than the page background. Used by Toast,
 * Tooltip, and other components that render on inverted surfaces.
 *
 * How it works:
 * 1. Sets `data-xds-theme` to create a scope boundary — stops parent
 *    theme's @scope'd component overrides from reaching children
 * 2. Sets `data-xds-media="dark|light"` which the theme's generated CSS
 *    targets to apply the correct semantic token overrides
 * 3. Children (Button, Link, Text, etc.) pick up inverted tokens naturally
 *    through CSS custom property inheritance
 *
 * The on-media token overrides are generated at theme definition time
 * via defineTheme() — no runtime computation needed.
 *
 * @example
 * ```tsx
 * // Dark surface (e.g. toast on a light page)
 * <div style={{ backgroundColor: 'var(--color-surface-inverted)' }}>
 *   <XDSMediaTheme surface="dark">
 *     <XDSButton label="Undo" variant="ghost" />
 *   </XDSMediaTheme>
 * </div>
 * ```
 */

import * as React from 'react';
import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  root: {
    display: 'contents',
  },
});

export interface XDSMediaThemeProps {
  /**
   * The surface luminance context for children.
   * - `"dark"` — children are on a dark background (get light text/icons)
   * - `"light"` — children are on a light background (get dark text/icons)
   */
  surface: 'dark' | 'light';
  /** Content to render in the media context */
  children: React.ReactNode;
}

/**
 * Inverted surface theming context.
 *
 * Wraps children in a scope boundary with the correct semantic token
 * overrides for the given surface luminance. No runtime token computation —
 * overrides are pre-generated by defineTheme() and applied via CSS.
 */
export function XDSMediaTheme({
  surface,
  children,
}: XDSMediaThemeProps): React.ReactElement {
  return (
    <div
      data-xds-theme="__media"
      data-xds-media={surface}
      {...stylex.props(styles.root)}>
      {children}
    </div>
  );
}

XDSMediaTheme.displayName = 'XDSMediaTheme';
