/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Thumbnail — Clickable
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Thumbnail/ThumbnailClickable';
