/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Chat — System Message With Divider
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Chat/ChatSystemMessageWithDivider';
