/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Dialog — Basic With Layout
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Dialog/DialogBasicWithLayout';
