/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Switch — Settings panel style (label start, spread spacing)
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Switch/SwitchSettingsPanelStyleLabelStartSpreadSpacing';
