/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Card — Muted Background
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Card/CardMutedBackground';
