/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TopNav — Basic nav with heading and items
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TopNav/TopNavBasicNavWithHeadingAndItems';
