/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MultiSelector — Basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MultiSelector/MultiSelectorBasic';
