/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Stack — StyleX utility — advanced use
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Stack/StackStyleXUtilityAdvancedUse';
