/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: SideNav — With XDSAppShell + TopNav (no header)
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/SideNav/SideNavWithXDSAppShellTopNavNoHeader';
