/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DateInput — Two-Month Calendar
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DateInput/DateInputTwoMonthCalendar';
