/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Toolbar — With XDSOverflowList for responsive collapsing
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Toolbar/ToolbarWithXDSOverflowListForResponsiveCollapsing';
