/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ProgressBar — Custom Value Label Formatter
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ProgressBar/ProgressBarCustomValueLabelFormatter';
