/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Section — Wash Variant
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Section/SectionWashVariant';
