/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Chat — Basic Conversation
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Chat/ChatBasicConversation';
