/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Thumbnail — Image with remove
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Thumbnail/ThumbnailImageWithRemove';
