/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Popover — Sibling Mode With Anchor Ref
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Popover/PopoverSiblingModeWithAnchorRef';
