/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MultiSelector — With Select All And Search
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MultiSelector/MultiSelectorWithSelectAllAndSearch';
