/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Timestamp — System date/time
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Timestamp/TimestampSystemDatetime';
