/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: RadioList — Horizontal Layout
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/RadioList/RadioListHorizontalLayout';
