/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Table — Children mode
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Table/TableChildrenMode';
