/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MoreMenu — Minimal Actions
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MoreMenu/MoreMenuMinimalActions';
