/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Dialog — Static Position
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Dialog/DialogStaticPosition';
