/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — With Units Display
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputWithUnitsDisplay';
