/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Section — With Dividers
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Section/SectionWithDividers';
