/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Icon — Semantic Names
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Icon/IconSemanticNames';
