/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Grid — Responsive Auto-Fit
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Grid/GridResponsiveAutoFit';
