/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AppShell — Responsive MobileNav
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AppShell/AppShellResponsiveMobileNav';
