/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Grid — Auto-Fit Max Columns
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Grid/GridAutoFitMaxColumns';
