/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: SegmentedControl — Disabled
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/SegmentedControl/SegmentedControlDisabled';
