// Copyright (c) Meta Platforms, Inc. and affiliates.
// @generated by .github/scripts/visual-gate/generate-probe-theme.mjs — do not edit.
//
// The non-component axes of the probe theme, generated from
// .github/scripts/visual-gate/lib/probe-axes.mjs.

import type {SyntaxThemeTokenInput} from '@astryxdesign/core/theme';

/** Tokens the probe overrides, observable on any themed subtree. */
export const PROBE_TOKENS: Record<string, string> = {
  '--color-accent': 'rgb(255, 0, 128)',
  '--color-background-body': 'rgb(0, 32, 16)',
  '--color-text-primary': 'rgb(240, 255, 0)',
  '--color-border': 'rgb(0, 224, 255)',
  '--radius-element': '13px',
  '--spacing-4': '17px',
  '--duration-fast': '11ms',
  '--font-size-base': '15.5px',
};

/** A font stack that can only have come from the theme. */
export const PROBE_FONT = '"AstryxProbeFace", monospace';

// Not annotated: the literal keys and tuple shapes ARE the contract
// (SyntaxThemeTokenInput requires all fourteen), so widening this to a Record
// would hide a missing token behind a type that accepts anything.
/** Syntax-token colours as [light, dark] pairs, one unmistakable value each. */
export const PROBE_SYNTAX: SyntaxThemeTokenInput = {
  keyword: ['hsl(0 100% 45%)', 'hsl(0 100% 65%)'],
  string: ['hsl(26 100% 45%)', 'hsl(26 100% 65%)'],
  comment: ['hsl(51 100% 45%)', 'hsl(51 100% 65%)'],
  number: ['hsl(77 100% 45%)', 'hsl(77 100% 65%)'],
  function: ['hsl(103 100% 45%)', 'hsl(103 100% 65%)'],
  type: ['hsl(129 100% 45%)', 'hsl(129 100% 65%)'],
  variable: ['hsl(154 100% 45%)', 'hsl(154 100% 65%)'],
  operator: ['hsl(180 100% 45%)', 'hsl(180 100% 65%)'],
  constant: ['hsl(206 100% 45%)', 'hsl(206 100% 65%)'],
  tag: ['hsl(231 100% 45%)', 'hsl(231 100% 65%)'],
  attribute: ['hsl(257 100% 45%)', 'hsl(257 100% 65%)'],
  property: ['hsl(283 100% 45%)', 'hsl(283 100% 65%)'],
  punctuation: ['hsl(309 100% 45%)', 'hsl(309 100% 65%)'],
  background: ['hsl(334 100% 45%)', 'hsl(334 100% 65%)'],
};
