// @generated by scripts/gen-api-types.mjs from the JSDoc in api/**/*.mjs.
// DO NOT EDIT — run `pnpm gen:api-types` to regenerate.

/**
 * @param {string} topic
 * @param {string} sectionName
 * @param {object} [options]
 * @param {string} [options.lang]
 * @param {boolean} [options.zh]
 * @param {boolean} [options.dense]
 * @returns {Promise<import('../../docs.type.mjs').DocsDetailSectionResponse>}
 */
export function section(topic: string, sectionName: string, options?: {
    lang?: string | undefined;
    zh?: boolean | undefined;
    dense?: boolean | undefined;
}): Promise<import("../../docs.type.mjs").DocsDetailSectionResponse>;
