/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Toast — With action
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Toast/ToastWithAction';
