/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Link — Inline With Text
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Link/LinkInlineWithText';
