/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextArea — With placeholder and custom rows
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextArea/TextAreaWithPlaceholderAndCustomRows';
