/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AspectRatio — Video
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AspectRatio/AspectRatioVideo';
