/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MoreMenu — Table Row Actions With Icons
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MoreMenu/MoreMenuTableRowActionsWithIcons';
