/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Switch — With error status
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Switch/SwitchWithErrorStatus';
