/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Tokenizer — Free-text tags (hasCreate)
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Tokenizer/TokenizerFreetextTagsHasCreate';
