/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DateInput — With Error Status
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DateInput/DateInputWithErrorStatus';
