/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CheckboxList — Disabled Group
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CheckboxList/CheckboxListDisabledGroup';
