/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Spinner — Rich label with composition
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Spinner/SpinnerRichLabelWithComposition';
