/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Skeleton — Basic text placeholder
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Skeleton/SkeletonBasicTextPlaceholder';
