/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Skeleton — Circular avatar placeholder
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Skeleton/SkeletonCircularAvatarPlaceholder';
