/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CheckboxInput — Small Size
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CheckboxInput/CheckboxInputSmallSize';
