/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextInput — Basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextInput/TextInputBasic';
