/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ToggleButton — Icon-only toggle
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ToggleButton/ToggleButtonIcononlyToggle';
