/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Typeahead — With custom item rendering
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Typeahead/TypeaheadWithCustomItemRendering';
