/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Slider — Vertical orientation
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Slider/SliderVerticalOrientation';
