/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: PowerSearch — Basic With Enum Filters
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/PowerSearch/PowerSearchBasicWithEnumFilters';
