/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Layout — Basic Page
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Layout/LayoutBasicPage';
