/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AppShell — TopNav + SideNav
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AppShell/AppShellTopNavSideNav';
