/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Pagination — Count Display With Page Size Selector
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Pagination/PaginationCountDisplayWithPageSizeSelector';
