/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Slider — With custom formatting
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Slider/SliderWithCustomFormatting';
