/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: FormLayout — Vertical Layout
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/FormLayout/FormLayoutVerticalLayout';
