/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: SideNav — Collapsible sidebar
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/SideNav/SideNavCollapsibleSidebar';
