/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Center — Both Axes
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Center/CenterBothAxes';
