/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: RadioList — With Status
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/RadioList/RadioListWithStatus';
