/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Avatar — Initials Fallback
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Avatar/AvatarInitialsFallback';
