/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TreeList — Basic tree
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TreeList/TreeListBasicTree';
