/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextArea — With character counter
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextArea/TextAreaWithCharacterCounter';
