/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: IconButton — Primary With Tooltip
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/IconButton/IconButtonPrimaryWithTooltip';
