/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AppShell — TopNav Only
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AppShell/AppShellTopNavOnly';
