/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: SegmentedControl — With Icons
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/SegmentedControl/SegmentedControlWithIcons';
