/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: FormLayout — Nested Layouts
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/FormLayout/FormLayoutNestedLayouts';
