/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — With Placeholder
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputWithPlaceholder';
