/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Markdown — Basic Usage
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Markdown/MarkdownBasicUsage';
