/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Avatar — With Image
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Avatar/AvatarWithImage';
