/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextArea — With description and optional indicator
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextArea/TextAreaWithDescriptionAndOptionalIndicator';
