/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Toolbar — Compact density
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Toolbar/ToolbarCompactDensity';
