/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MobileNav — Responsive Sidebar Drawer Pattern
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MobileNav/MobileNavResponsiveSidebarDrawerPattern';
