/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Selector — Custom Rendering
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Selector/SelectorCustomRendering';
