/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Carousel — No Buttons
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Carousel/CarouselNoButtons';
