'use client';

import {useState, useMemo} from 'react';
import * as stylex from '@stylexjs/stylex';
import {colorVars, radiusVars} from '@xds/core/theme/tokens.stylex';
import {XDSAppShell} from '@xds/core/AppShell';
import {
  XDSSideNav,
  XDSSideNavItem,
  XDSSideNavSection,
  XDSSideNavCollapseButton,
} from '@xds/core/SideNav';
import {XDSVStack, XDSHStack} from '@xds/core/Layout';
import {XDSText, XDSHeading} from '@xds/core/Text';
import {XDSButton} from '@xds/core/Button';
import {XDSPowerSearch, usePowerSearchConfig} from '@xds/core/PowerSearch';
import type {PowerSearchFilter} from '@xds/core/PowerSearch';
import {XDSNavIcon} from '@xds/core/NavIcon';
import {
  XDSTable,
  useXDSTableSelection,
  useXDSTableSortable,
  proportional,
  pixel,
} from '@xds/core/Table';
import type {XDSTableColumn} from '@xds/core/Table';

// Icons
const UsersIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={1.5}
    {...props}>
    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
    <circle cx="9" cy="7" r="4" />
    <path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75" />
  </svg>
);
const InboxIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={1.5}
    {...props}>
    <polyline points="22 12 16 12 14 15 10 15 8 12 2 12" />
    <path d="M5.45 5.11L2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" />
  </svg>
);
const TagIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={1.5}
    {...props}>
    <path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z" />
    <line x1="7" y1="7" x2="7.01" y2="7" />
  </svg>
);
const SettingsIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={1.5}
    {...props}>
    <circle cx="12" cy="12" r="3" />
    <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
  </svg>
);
const FilterIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={1.5}
    {...props}>
    <line x1="4" y1="6" x2="20" y2="6" />
    <line x1="7" y1="12" x2="17" y2="12" />
    <line x1="10" y1="18" x2="14" y2="18" />
  </svg>
);
const DownloadIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={1.5}
    {...props}>
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
);
const ColumnsIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={1.5}
    {...props}>
    <rect x="3" y="3" width="7" height="18" rx="1" />
    <rect x="14" y="3" width="7" height="18" rx="1" />
  </svg>
);

// Types
interface DogRow extends Record<string, unknown> {
  id: string;
  name: string;
  breed: string;
  biography: string;
  age: number;
}

// Mock data
const allDogs: DogRow[] = [
  {
    id: '1',
    name: 'Adam',
    breed: 'Labrador',
    biography:
      'I love relaxing in the park and hate skateboards -- you might wonder how well those things mix and the answer is "not that well."',
    age: 17,
  },
  {
    id: '2',
    name: 'Al Chihuahua',
    breed: 'Chihuahua',
    biography: 'This is a Chihuahua generated by meta.ai',
    age: 2,
  },
  {
    id: '3',
    name: 'Archer',
    breed: 'Doberman',
    biography:
      "I'm an 8 year old Greater Swiss Mountain Dog and I live in Mountain View with my mom and dad.",
    age: 9,
  },
  {
    id: '4',
    name: 'Archie',
    breed: 'Australian Shepherd',
    biography: 'border collie',
    age: 5,
  },
  {
    id: '5',
    name: 'Argos',
    breed: 'Labrador',
    biography: 'Faithful hunting dog',
    age: 23,
  },
  {
    id: '6',
    name: 'Ball hunter',
    breed: 'Labrador',
    biography: 'This is a test bio',
    age: 5,
  },
  {
    id: '7',
    name: 'Banjo',
    breed: 'Poodle',
    biography:
      "Banjo was a rescue, approx 2 yo from Underdog Rescue in Concord, CA. He's a loving poodle mix that loves to run on the beach and travel with us.",
    age: 9,
  },
  {
    id: '8',
    name: 'Barley',
    breed: 'Maltese',
    biography: 'Teacup dog that I love!',
    age: 4,
  },
  {
    id: '9',
    name: 'Beast',
    breed: 'Bulldog',
    biography: 'Summers in Palo Alto',
    age: 14,
  },
  {
    id: '10',
    name: 'Belki Rodnik Mountford-Blake',
    breed: 'Pomsky',
    biography: 'Belki is actually three squirrels in an overcoat.',
    age: 6,
  },
  {id: '11', name: 'Bella', breed: 'Doberman', biography: 'Good girl', age: 10},
  {
    id: '12',
    name: 'Billy',
    breed: 'Bulldog',
    biography: 'Hi, I am Billy.',
    age: 5,
  },
  {
    id: '13',
    name: 'Brienne',
    breed: 'Dachshund',
    biography: 'Brienne of Bark the cream mini dachshund',
    age: 7,
  },
  {
    id: '14',
    name: 'Bruno',
    breed: 'Poodle',
    biography:
      "Bruno is a shih tzu. He's a smart doggo, I never needed more than a day to teach him a trick. He loves chicken and is always demanding a play.",
    age: 5,
  },
  {
    id: '15',
    name: 'Cabo',
    breed: 'Poodle',
    biography: 'Cabo is a mix of Terrier, Poodle, and unknown. Fat and grumpy.',
    age: 9,
  },
  {
    id: '16',
    name: 'Chai',
    breed: 'Shiba Inu',
    biography: 'Sunshine and hiking',
    age: 0,
  },
  {
    id: '17',
    name: 'Charlie',
    breed: 'Golden Retriever',
    biography: 'The goodest boy in the whole wide world.',
    age: 3,
  },
  {
    id: '18',
    name: 'Coco',
    breed: 'French Bulldog',
    biography: 'Loves naps and belly rubs.',
    age: 6,
  },
  {
    id: '19',
    name: 'Daisy',
    breed: 'Beagle',
    biography: 'Will follow any scent trail anywhere.',
    age: 8,
  },
  {
    id: '20',
    name: 'Duke',
    breed: 'German Shepherd',
    biography: 'Guard dog by day, couch potato by night.',
    age: 11,
  },
  {
    id: '21',
    name: 'Ella',
    breed: 'Corgi',
    biography: 'Short legs, big personality.',
    age: 4,
  },
  {
    id: '22',
    name: 'Finn',
    breed: 'Husky',
    biography: 'Loves snow and howling at the moon.',
    age: 7,
  },
  {
    id: '23',
    name: 'Ginger',
    breed: 'Irish Setter',
    biography: 'Red and rambunctious.',
    age: 5,
  },
  {
    id: '24',
    name: 'Hank',
    breed: 'Basset Hound',
    biography: 'Ears for days.',
    age: 9,
  },
  {
    id: '25',
    name: 'Izzy',
    breed: 'Border Collie',
    biography: 'Smarter than most people I know.',
    age: 3,
  },
  {
    id: '26',
    name: 'Jax',
    breed: 'Pit Bull',
    biography: 'Gentle giant who loves kids.',
    age: 6,
  },
  {
    id: '27',
    name: 'Koda',
    breed: 'Akita',
    biography: 'Loyal and fluffy.',
    age: 8,
  },
  {
    id: '28',
    name: 'Luna',
    breed: 'Samoyed',
    biography: 'Cloud on four legs.',
    age: 2,
  },
  {
    id: '29',
    name: 'Max',
    breed: 'Rottweiler',
    biography: 'Big softie.',
    age: 10,
  },
  {
    id: '30',
    name: 'Nala',
    breed: 'Labradoodle',
    biography: 'Hypoallergenic and proud of it.',
    age: 4,
  },
  {
    id: '31',
    name: 'Oscar',
    breed: 'Dachshund',
    biography: 'Long boy.',
    age: 12,
  },
  {
    id: '32',
    name: 'Penny',
    breed: 'Cavalier King Charles',
    biography: 'Lap dog extraordinaire.',
    age: 7,
  },
  {
    id: '33',
    name: 'Rex',
    breed: 'Doberman',
    biography: 'Fast and fearless.',
    age: 5,
  },
  {
    id: '34',
    name: 'Sadie',
    breed: 'Australian Shepherd',
    biography: 'Herds everything, including the cat.',
    age: 3,
  },
  {
    id: '35',
    name: 'Tucker',
    breed: 'Golden Retriever',
    biography: 'Tennis ball enthusiast.',
    age: 6,
  },
  {
    id: '36',
    name: 'Willow',
    breed: 'Greyhound',
    biography: 'Retired racer, full-time lounger.',
    age: 8,
  },
  {
    id: '37',
    name: 'Zeus',
    breed: 'Great Dane',
    biography: 'Thinks he is a lap dog.',
    age: 4,
  },
  {
    id: '38',
    name: 'Rosie',
    breed: 'Maltipoo',
    biography: 'Tiny but mighty.',
    age: 2,
  },
  {
    id: '39',
    name: 'Scout',
    breed: 'Labrador',
    biography: 'Adventure buddy.',
    age: 5,
  },
  {
    id: '40',
    name: 'Teddy',
    breed: 'Bernese Mountain Dog',
    biography: 'Gentle giant of the mountains.',
    age: 7,
  },
];

const breedValues = [
  {value: 'Labrador', label: 'Labrador'},
  {value: 'Chihuahua', label: 'Chihuahua'},
  {value: 'Doberman', label: 'Doberman'},
  {value: 'Australian Shepherd', label: 'Australian Shepherd'},
  {value: 'Poodle', label: 'Poodle'},
  {value: 'Maltese', label: 'Maltese'},
  {value: 'Bulldog', label: 'Bulldog'},
  {value: 'Pomsky', label: 'Pomsky'},
  {value: 'Dachshund', label: 'Dachshund'},
  {value: 'Shiba Inu', label: 'Shiba Inu'},
  {value: 'Golden Retriever', label: 'Golden Retriever'},
  {value: 'French Bulldog', label: 'French Bulldog'},
  {value: 'Beagle', label: 'Beagle'},
  {value: 'German Shepherd', label: 'German Shepherd'},
  {value: 'Corgi', label: 'Corgi'},
  {value: 'Husky', label: 'Husky'},
];

const fieldDefs = [
  {key: 'name', type: 'string', label: 'Name'},
  {key: 'breed', type: 'enum', label: 'Breed', enumValues: breedValues},
  {key: 'biography', type: 'string', label: 'Biography'},
] as const;

const DogIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width="20"
    height="20"
    {...props}>
    <path
      fill="currentColor"
      d="M20 5h-.26c-.31-.57-.9-1-1.74-1h-3.02l-1.16-1.45c-.35-.43-.9-.63-1.44-.52s-.96.51-1.11 1.05c-.31 1.14-.6 2.86-.25 4.62.26 1.29-.14 2-.41 2.3H7.87C6.7 8.97 6.64 7.62 6.98 5.67a.99.99 0 0 0-.22-.81 1 1 0 0 0-.77-.36c-1.59 0-2.88.82-3.54 2.25-1.03 2.26-.3 5.51 1.77 7.9h.01L3.36 19c-.15.74.04 1.49.52 2.08s1.18.92 1.93.92h.3c.9 0 1.73-.48 2.17-1.26l1.39-2.43c1.2-.4 2.22-.42 3.1-.04l1.41 2.47A2.5 2.5 0 0 0 16.35 22h.4c.73 0 1.41-.31 1.89-.86s.69-1.27.59-1.99l-.75-5.22V12.5c1.93 0 3.5-1.57 3.5-3.5V7c0-1.1-.9-2-2-2zM4.28 7.58c.14-.3.31-.53.53-.71-.07 1.15.07 2.55.96 3.79-.43.34-.76.8-.95 1.34-.91-1.67-1.01-3.37-.54-4.41zm12.87 12.25a.52.52 0 0 1-.38.17h-.4c-.18 0-.35-.1-.43-.25l-1.57-2.74c-.1-.17-.24-.3-.41-.39-.78-.41-1.63-.61-2.54-.61s-1.8.19-2.78.56c-.21.08-.39.24-.51.44l-1.57 2.74c-.09.16-.25.25-.43.25h-.3c-.21 0-.33-.11-.39-.18a.47.47 0 0 1-.1-.41l1.32-6.6c.09-.47.51-.8.98-.8h3.31c1.11 1.65 2.82 2.52 5 2.52.2 0 .41 0 .62-.02l.7 4.93c.03.2-.06.33-.12.4zM20 9c0 .83-.67 1.5-1.5 1.5H18c-.83 0-1.5.67-1.5 1.5v.51s-.05-.01-.07 0c-1.85.14-3.09-.43-3.91-1.76.43-.73.78-1.86.46-3.44-.18-.92-.13-1.86-.01-2.62l.75.94a1 1 0 0 0 .78.38H18c0 .55.45 1 1 1h1v2z"
    />
    <path fill="currentColor" d="M16 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
  </svg>
);

// Columns
const columns: XDSTableColumn<DogRow>[] = [
  {
    key: 'name',
    header: 'Name',
    width: proportional(2),
    renderCell: (item: DogRow) => (
      <XDSHStack gap={3} vAlign="center">
        <div {...stylex.props(styles.dogIconWrapper)}>
          <DogIcon />
        </div>
        <XDSVStack gap={0}>
          <XDSText type="body">{item.name}</XDSText>
          <XDSText type="supporting" color="secondary">
            {item.breed}
          </XDSText>
        </XDSVStack>
      </XDSHStack>
    ),
  },
  {
    key: 'biography',
    header: 'Biography',
    width: proportional(5),
    renderCell: (item: DogRow) => (
      <XDSText type="body">{item.biography}</XDSText>
    ),
  },
  {
    key: 'age',
    header: 'Age',
    width: pixel(80),
    renderCell: (item: DogRow) => (
      <XDSText type="body" style={{textAlign: 'right', display: 'block'}}>
        {item.age}
      </XDSText>
    ),
  },
];

const styles = stylex.create({
  bulkBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 16px',
    borderRadius: radiusVars['--radius-element'],
    backgroundColor: colorVars['--color-background-muted'],
  },
  dogIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: radiusVars['--radius-full'],
    backgroundColor: colorVars['--color-background-muted'],
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },

  headerPadding: {
    padding: 16,
  },
});

function DataTableSideNav() {
  const [active, setActive] = useState('users');
  return (
    <XDSSideNav
      header={
        <div
          style={{
            padding: '12px 16px',
            display: 'flex',
            alignItems: 'center',
            gap: 8,
          }}>
          <XDSNavIcon icon={<UsersIcon style={{width: 16, height: 16}} />} />
          <XDSText type="body" weight="bold">
            Admin
          </XDSText>
        </div>
      }
      footer={<XDSSideNavCollapseButton />}>
      <XDSSideNavSection title="Manage">
        <XDSSideNavItem
          label="Users"
          icon={UsersIcon}
          isSelected={active === 'users'}
          onClick={() => setActive('users')}
        />
        <XDSSideNavItem
          label="Invitations"
          icon={InboxIcon}
          isSelected={active === 'invitations'}
          onClick={() => setActive('invitations')}
        />
        <XDSSideNavItem
          label="Roles"
          icon={TagIcon}
          isSelected={active === 'roles'}
          onClick={() => setActive('roles')}
        />
      </XDSSideNavSection>
      <XDSSideNavSection title="System">
        <XDSSideNavItem
          label="Settings"
          icon={SettingsIcon}
          isSelected={active === 'settings'}
          onClick={() => setActive('settings')}
        />
      </XDSSideNavSection>
    </XDSSideNav>
  );
}

export default function DataTableTemplate() {
  const [filters, setFilters] = useState<PowerSearchFilter[]>([]);
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(new Set());

  const {config, applyFilters} = usePowerSearchConfig(fieldDefs, 'Dogs');

  const filtered = useMemo(() => {
    return applyFilters(filters, allDogs);
  }, [filters, applyFilters]);

  const selectionPlugin = useXDSTableSelection<DogRow>({
    getIsItemSelected: (item: DogRow) => selectedKeys.has(item.id),
    onSelectItem: ({item, isSelected}: {item: DogRow; isSelected: boolean}) => {
      setSelectedKeys(prev => {
        const next = new Set(prev);
        if (isSelected) {
          next.add(item.id);
        } else {
          next.delete(item.id);
        }
        return next;
      });
    },
    onSelectAll: ({isAllSelected}: {isAllSelected: boolean}) => {
      setSelectedKeys(prev => {
        const next = new Set(prev);
        if (isAllSelected) filtered.forEach(r => next.add(r.id));
        else filtered.forEach(r => next.delete(r.id));
        return next;
      });
    },
    getIsAllSelected: () =>
      filtered.length > 0 && filtered.every(r => selectedKeys.has(r.id)),
    getIsIndeterminate: () => {
      const c = filtered.filter(r => selectedKeys.has(r.id)).length;
      return c > 0 && c < filtered.length;
    },
  });

  const plugins = useMemo(
    () => ({selection: selectionPlugin}),
    [selectionPlugin],
  );

  return (
    <XDSAppShell
      sideNav={<DataTableSideNav />}
      variant="elevated"
      contentPadding={0}>
      <XDSVStack gap={0}>
        <XDSVStack gap={2} xstyle={styles.headerPadding}>
          <XDSHStack gap={3} vAlign="center">
            <div style={{flex: 1}}>
              <XDSHeading level={1}>Dogs</XDSHeading>
            </div>
          </XDSHStack>

          <XDSHStack gap={2} vAlign="center">
            <div style={{flex: 1}}>
              <XDSPowerSearch
                config={config}
                filters={filters}
                onChange={newFilters => {
                  setFilters([...newFilters]);
                }}
                placeholder="Search..."
                resultCount={filtered.length}
              />
            </div>
            <XDSButton
              label="Filter"
              icon={<FilterIcon style={{width: 16, height: 16}} />}
            />
            <XDSButton
              label="Download"
              icon={<DownloadIcon style={{width: 16, height: 16}} />}
            />
            <XDSButton
              label="View options"
              icon={<SettingsIcon style={{width: 16, height: 16}} />}>
              View options
            </XDSButton>
          </XDSHStack>
        </XDSVStack>

        {selectedKeys.size > 0 && (
          <div {...stylex.props(styles.bulkBar)}>
            <XDSText type="supporting" weight="bold">
              {selectedKeys.size} selected
            </XDSText>
            <XDSHStack gap={2}>
              <XDSButton label="Deactivate" variant="ghost" size="sm" />
              <XDSButton label="Delete" variant="ghost" size="sm" />
            </XDSHStack>
          </div>
        )}

        <XDSTable<DogRow>
          data={filtered}
          columns={columns}
          idKey="id"
          density="balanced"
          dividers="rows"
          hasHover
          plugins={plugins}
        />
      </XDSVStack>
    </XDSAppShell>
  );
}
