/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TimeInput — Min / max constraints
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TimeInput/TimeInputMinMaxConstraints';
