/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: StatusDot — With pulse
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/StatusDot/StatusDotWithPulse';
