/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AlertDialog — Imperative
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AlertDialog/AlertDialogImperative';
