/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: List — With Dividers And Header
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/List/ListWithDividersAndHeader';
