/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Dialog — Required Purpose
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Dialog/DialogRequiredPurpose';
