import {defineTheme} from '@xds/core/theme';
import {dailyIconRegistry} from './icons';

export const dailyTheme = defineTheme({
  name: 'daily',
  typography: {scale: {base: 16, ratio: 1.25}},
  tokens: {
    '--color-accent': '#5B9BFF',
    '--color-background-body': ['#F9F6EF', '#141414'],
    '--color-text-primary': '#322F26',
    '--color-neutral': '#F9F6EF',
    '--color-background-muted': 'rgba(160, 110, 0, 0.08)',
    '--color-background-gray': '#F9F6EF',
    '--color-border-emphasized': 'rgba(72, 66, 51, 0.3)',
    '--color-warning': '#F2BA02',
    '--spacing-0-5': '3px',
    '--spacing-1': '6px',
    '--spacing-1-5': '9px',
    '--spacing-2': '12px',
    '--spacing-3': '18px',
    '--spacing-4': '24px',
    '--spacing-5': '30px',
    '--spacing-6': '36px',
    '--spacing-7': '42px',
    '--spacing-8': '48px',
    '--spacing-9': '54px',
    '--spacing-10': '60px',
    '--spacing-11': '66px',
    '--spacing-12': '72px',
    '--radius-inner': '6px',
    '--radius-element': '12px',
    '--radius-container': '18px',
    '--radius-page': '42px',
    '--font-family-body':
      'Figtree, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    '--font-family-heading':
      'Figtree, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    '--font-size-4xs': '0.3125rem',
    '--font-size-sm': '0.8125rem',
    '--font-size-base': '1rem',
    '--font-size-lg': '1.25rem',
    '--font-size-xl': '1.5625rem',
    '--font-size-2xl': '1.9375rem',
    '--font-size-3xl': '2.4375rem',
    '--font-size-4xl': '3.0625rem',
    '--font-size-5xl': '3.8125rem',
    '--size-element-sm': '34px',
    '--size-element-md': '40px',
    '--size-element-lg': '46px',
    '--duration-fast-min': '115ms',
    '--duration-fast': '150ms',
    '--duration-fast-max': '200ms',
    '--duration-medium-min': '265ms',
    '--duration-medium': '350ms',
    '--duration-medium-max': '465ms',
    '--duration-slow-min': '600ms',
    '--duration-slow': '800ms',
    '--duration-slow-max': '1065ms',
  },
  components: {
    button: {
      base: {
        borderRadius: 'var(--radius-full)',
      },
      'variant:primary': {
        backgroundColor: '#322F26',
        color: '#FFFFFF',
      },
      'variant:secondary': {
        backgroundColor: 'transparent',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: '#322F26',
        color: '#322F26',
      },
    },
  },
  icons: dailyIconRegistry,
});
