/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Breadcrumbs — With Icons
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Breadcrumbs/BreadcrumbsWithIcons';
