/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Token — As link
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Token/TokenAsLink';
