/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Carousel — With Snap
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Carousel/CarouselWithSnap';
