/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Popover — Controlled
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Popover/PopoverControlled';
