/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MoreMenu — With Sections
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MoreMenu/MoreMenuWithSections';
