/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ToggleButton — Icon swap on press
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ToggleButton/ToggleButtonIconSwapOnPress';
