/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextInput — Hidden label
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextInput/TextInputHiddenLabel';
