/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TreeList — Interactive items
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TreeList/TreeListInteractiveItems';
