/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Switch — With label icon and tooltip
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Switch/SwitchWithLabelIconAndTooltip';
