/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Slider — With step and marks
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Slider/SliderWithStepAndMarks';
