/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NavIcon — In Side Navigation
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NavIcon/NavIconInSideNavigation';
