/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: FormLayout — Horizontal Labels
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/FormLayout/FormLayoutHorizontalLabels';
