/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Slider — Range with minimum gap
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Slider/SliderRangeWithMinimumGap';
