/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — Integer Only
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputIntegerOnly';
