'use client';

import {XDSTable} from '@xds/core/Table';

const users = [
  {name: 'Alice', email: 'alice@example.com', role: 'Admin'},
  {name: 'Bob', email: 'bob@example.com', role: 'User'},
];

export default function TableAutogeneratedColumns() {
  return (
    <XDSTable data={users} isStriped />
  );
}
