'use client';

import {XDSTable} from '@xds/core/Table';

const users = [
  {name: 'Alice', email: 'alice@example.com', role: 'Admin'},
  {name: 'Bob', email: 'bob@example.com', role: 'User'},
];

export default function TableAutogeneratedColumns() {
  return (
    // @ts-expect-error migrated example
    // @ts-expect-error migrated example
    <XDSTable data={users} isStriped />
  );
}

export const showcase = {
  aspectRatio: 4 / 3,
  render: TableAutogeneratedColumns,
};
