/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Dialog — Fullscreen Variant
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Dialog/DialogFullscreenVariant';
