/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MoreMenu — Card Header With Overflow Menu
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MoreMenu/MoreMenuCardHeaderWithOverflowMenu';
