/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Card — Simple Content
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Card/CardSimpleContent';
