/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Tooltip — XDSTooltip — basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Tooltip/TooltipXDSTooltipBasic';
