/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Grid — Fixed Columns
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Grid/GridFixedColumns';
