/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ProgressBar — With Visible Value Label
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ProgressBar/ProgressBarWithVisibleValueLabel';
