/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Center — Inline
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Center/CenterInline';
