/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Collapsible — Single Mode Accordion
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Collapsible/CollapsibleSingleModeAccordion';
