/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MetadataList — With Title And Show More
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MetadataList/MetadataListWithTitleAndShowMore';
