/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CodeBlock — Inline Code In Text
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CodeBlock/CodeBlockInlineCodeInText';
