/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: EmptyState — Compact Variant
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/EmptyState/EmptyStateCompactVariant';
