/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Layout — App Shell With Sidebar
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Layout/LayoutAppShellWithSidebar';
