/**
 * Minimal default theme — relies on auto-generated typography
 */
import {defineTheme} from '@xds/core/theme';

export const defaultMinimalTheme = defineTheme({
  name: 'default-minimal',
  // No tokens — all defaults
  // No components — typography auto-generated by build
  components: {
    button: {
      'variant:secondary': {
        backgroundColor:
          'light-dark(rgba(5, 54, 89, 0.1), rgba(223, 226, 229, 0.2))',
      },
    },
  },
});
