/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ProgressBar — Semantic Variant
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ProgressBar/ProgressBarSemanticVariant';
