/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TopNav — With hover menu and mega menu
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TopNav/TopNavWithHoverMenuAndMegaMenu';
