/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MoreMenu — Custom Item Rendering
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MoreMenu/MoreMenuCustomItemRendering';
