/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Switch — With async action and optimistic UI
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Switch/SwitchWithAsyncActionAndOptimisticUI';
