/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextArea — Hidden label
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextArea/TextAreaHiddenLabel';
