/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: HoverCard — Hook
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/HoverCard/HoverCardHook';
