/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — Required Field
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputRequiredField';
