/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextInput — With placeholder
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextInput/TextInputWithPlaceholder';
