/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — With Event Handlers
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputWithEventHandlers';
