/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Selector — With Status And Field Props
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Selector/SelectorWithStatusAndFieldProps';
