// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * @file Colocated tests for the theme-drift checks.
 *
 * Roughly half of these are negative controls, deliberately. A detector that
 * only proves it finds things says nothing about whether it will bury the
 * reader in noise, and every false positive here is one an agent would act on.
 */

import {describe, it, expect, afterEach} from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  scanConsumerCss,
  findSwizzled,
  checkCssEscapes,
  checkSwizzled,
} from './theme-drift.mjs';

const tmpDirs = [];
function mkProject(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'astryx-drift-'));
  tmpDirs.push(dir);
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(dir, rel);
    fs.mkdirSync(path.dirname(abs), {recursive: true});
    fs.writeFileSync(abs, content);
  }
  return dir;
}
afterEach(() => {
  while (tmpDirs.length) fs.rmSync(tmpDirs.pop(), {recursive: true, force: true});
});

const ctx = cwd => ({cwd, nodeVersion: '', coreDir: null, configPath: null, configTheme: null});
const kinds = findings => findings.map(f => f.kind);

describe('scanConsumerCss — negative controls', () => {
  it('passes legitimate consumer CSS', () => {
    const dir = mkProject({
      'src/app.css': [
        // App-local custom properties are not system tokens.
        ':root { --app-sidebar: 260px; --app-max: 1200px; }',
        // Consuming tokens is correct; only *defining* them globally is not.
        '.shell { gap: var(--spacing-4); background: var(--color-background-body); }',
        // The data-attribute surface is the sanctioned one.
        '.astryx-button[data-variant="primary"] { letter-spacing: 0.01em; }',
        // Scoped theme overrides are exactly right.
        '[data-astryx-theme="brand"] { --app-glow: 0 0 12px var(--color-accent); }',
      ].join('\n'),
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });

  it('does not flag a consumer class chained onto an Astryx class', () => {
    // `.astryx-card.promo` is the consumer's own class, not a legacy prop class.
    const dir = mkProject({'src/a.css': '.astryx-card.promo { outline: 1px solid red; }'});
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });

  it('ignores a token name that only appears inside a comment', () => {
    const dir = mkProject({
      'src/a.css': '/* never write --color-accent: #000 in :root */\n.x { color: red; }',
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });

  it('ignores generated theme output, which legitimately contains both', () => {
    // The pipeline emits private vars and bare prop classes. Judging the
    // tool's own output as consumer error was the largest false-positive
    // source when this was first built.
    const dir = mkProject({
      'src/themes/app.css': [
        '/*',
        ' * @generated by `astryx theme build` — do not edit manually.',
        ' */',
        '.astryx-button { --_button-radius: 8px; }',
        '.astryx-top-nav-item.selected { color: red; }',
      ].join('\n'),
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });

  it('ignores stylesheets inside node_modules and build output', () => {
    const bad = ':root { --color-accent: #f00; }';
    const dir = mkProject({
      'node_modules/pkg/a.css': bad,
      'dist/b.css': bad,
      '.next/c.css': bad,
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });
});

describe('scanConsumerCss — detection', () => {
  it('flags system tokens redefined in every global scope', () => {
    const dir = mkProject({
      'src/a.css': [
        ':root { --color-accent: #ff3366; --spacing-4: 18px; }',
        'html { --font-size-base: 15px; }',
        ':host { --radius-element: 3px; }',
      ].join('\n'),
    });
    const f = scanConsumerCss(dir).findings;
    expect(kinds(f)).toEqual(Array(4).fill('root-token-override'));
    expect(f.map(x => x.detail)).toEqual([
      '--color-accent', '--spacing-4', '--font-size-base', '--radius-element',
    ]);
  });

  it('flags writes to private implementation vars', () => {
    const dir = mkProject({'src/a.css': '.x { --_button-radius: 2px; }'});
    const [f] = scanConsumerCss(dir).findings;
    expect(f.kind).toBe('private-var-write');
    expect(f.detail).toBe('--_button-radius');
  });

  it('flags deprecated bare prop classes', () => {
    const dir = mkProject({
      'src/a.css': '.astryx-button.primary { text-transform: uppercase; }',
    });
    const [f] = scanConsumerCss(dir).findings;
    expect(f.kind).toBe('deprecated-bare-class');
    expect(f.detail).toBe('.astryx-button.primary');
  });

  it('reports the line in the original file, not the comment-stripped one', () => {
    // Stripping comments outright collapses lines and shifts every finding.
    const dir = mkProject({
      'src/a.css': ['/*', ' * a', ' * long', ' * banner', ' */', '', '.x { --_r: 1px; }'].join('\n'),
    });
    expect(scanConsumerCss(dir).findings[0].line).toBe(7);
  });
});

describe('checkCssEscapes', () => {
  it('skips a project with no stylesheets', () => {
    const c = checkCssEscapes(ctx(mkProject({'package.json': '{}'})));
    expect(c.status).toBe('info');
  });

  it('passes clean CSS', () => {
    const dir = mkProject({'src/a.css': '.x { color: var(--color-text-primary); }'});
    expect(checkCssEscapes(ctx(dir)).status).toBe('pass');
  });

  it('fails on private vars — matching what `theme build` already rejects', () => {
    const dir = mkProject({'src/a.css': '.x { --_card-radius: 0; }'});
    const c = checkCssEscapes(ctx(dir));
    expect(c.status).toBe('fail');
    expect(c.fix).toMatch(/defineTheme/);
  });

  it('warns, not fails, on a global token override', () => {
    const dir = mkProject({'src/a.css': ':root { --color-accent: #f00; }'});
    expect(checkCssEscapes(ctx(dir)).status).toBe('warn');
  });

  it('offers the data-attribute replacement for a bare class', () => {
    const dir = mkProject({'src/a.css': '.astryx-badge.success { font-weight: 700; }'});
    const c = checkCssEscapes(ctx(dir));
    expect(c.status).toBe('warn');
    expect(c.fix).toBe('Target the reflected data attribute instead: .astryx-badge[data-variant="success"].');
  });
});

describe('findSwizzled / checkSwizzled', () => {
  const swizzled = extra => ({
    'package.json': JSON.stringify({dependencies: {'@astryxdesign/core': '^0.3.0'}, ...extra}),
    'src/components/astryx/Button/Button.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Button() { return null; }",
    'src/components/astryx/Card/Card.tsx': 'export function Card() { return null; }',
  });

  it('finds swizzled component directories', () => {
    const {dirs, usesStyleX} = findSwizzled(mkProject(swizzled()));
    expect(dirs.map(d => path.basename(d)).sort()).toEqual(['Button', 'Card']);
    expect(usesStyleX).toBe(true);
  });

  it('fails when swizzled StyleX source has no compiler — it renders unstyled, silently', () => {
    const c = checkSwizzled(ctx(mkProject(swizzled())));
    expect(c.status).toBe('fail');
    expect(c.message).toMatch(/no StyleX compiler/i);
  });

  it('is only informational once a compiler is configured', () => {
    const dir = mkProject(swizzled({devDependencies: {'@stylexjs/babel-plugin': '^0.17.5'}}));
    expect(checkSwizzled(ctx(dir)).status).toBe('info');
  });

  it('passes a project with nothing swizzled', () => {
    const dir = mkProject({'package.json': '{}', 'src/App.tsx': 'export const A = 1;'});
    const c = checkSwizzled(ctx(dir));
    expect(c.status).toBe('pass');
    expect(c.fix).toBeUndefined();
  });

  it('does not mistake an unrelated directory named astryx for swizzle output', () => {
    // Only ./components/astryx/* is the swizzle target.
    const dir = mkProject({'package.json': '{}', 'src/astryx/helper.ts': 'export const x = 1;'});
    expect(findSwizzled(dir).dirs).toEqual([]);
  });
});
