// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * @file Colocated tests for the theme-drift checks.
 *
 * Roughly half of these are negative controls, deliberately. A detector that
 * only proves it finds things says nothing about whether it will bury the
 * reader in noise, and every false positive here is one an agent would act on.
 */

import {describe, it, expect, afterEach} from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {fileURLToPath} from 'node:url';
import {detectStylingSystem} from '../../foundation/agent-docs/agent-docs.mjs';
import {
  scanConsumerCss,
  findSwizzled,
  checkCssEscapes,
  checkSwizzled,
  resolveBareClasses,
} from './theme-drift.mjs';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../..');
const CORE_SRC = path.join(REPO, 'packages/core/src');

const tmpDirs = [];
function mkProject(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'astryx-drift-'));
  tmpDirs.push(dir);
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(dir, rel);
    fs.mkdirSync(path.dirname(abs), {recursive: true});
    fs.writeFileSync(abs, content);
  }
  return dir;
}
afterEach(() => {
  while (tmpDirs.length) fs.rmSync(tmpDirs.pop(), {recursive: true, force: true});
});

const ctx = cwd => ({cwd, nodeVersion: '', coreDir: null, configPath: null, configTheme: null});
const kinds = findings => findings.map(f => f.kind);

describe('scanConsumerCss — negative controls', () => {
  it('passes legitimate consumer CSS', () => {
    const dir = mkProject({
      'src/app.css': [
        // App-local custom properties are not system tokens.
        ':root { --app-sidebar: 260px; --app-max: 1200px; }',
        // Consuming tokens is correct; only *defining* them globally is not.
        '.shell { gap: var(--spacing-4); background: var(--color-background-body); }',
        // The data-attribute surface is the sanctioned one.
        '.astryx-button[data-variant="primary"] { letter-spacing: 0.01em; }',
        // Scoped theme overrides are exactly right.
        '[data-astryx-theme="brand"] { --app-glow: 0 0 12px var(--color-accent); }',
      ].join('\n'),
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });

  it('does not flag a consumer class chained onto an Astryx class', async () => {
    // `.astryx-card.promo` is the consumer's own class. `promo` is not a value
    // of any Card visual prop, so resolution drops it.
    const dir = mkProject({'src/a.css': '.astryx-card.promo { outline: 1px solid red; }'});
    const resolved = await resolveBareClasses(scanConsumerCss(dir).findings, CORE_SRC);
    expect(resolved).toEqual([]);
  });

  it('ignores a token name that only appears inside a comment', () => {
    const dir = mkProject({
      'src/a.css': '/* never write --color-accent: #000 in :root */\n.x { color: red; }',
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });

  it('ignores generated theme output, which legitimately contains both', () => {
    // The pipeline emits private vars and bare prop classes. Judging the
    // tool's own output as consumer error was the largest false-positive
    // source when this was first built.
    const dir = mkProject({
      'src/themes/app.css': [
        '/*',
        ' * @generated by `astryx theme build` — do not edit manually.',
        ' */',
        '.astryx-button { --_button-radius: 8px; }',
        '.astryx-top-nav-item.selected { color: red; }',
      ].join('\n'),
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });

  it('ignores stylesheets inside node_modules and build output', () => {
    const bad = ':root { --color-accent: #f00; }';
    const dir = mkProject({
      'node_modules/pkg/a.css': bad,
      'dist/b.css': bad,
      '.next/c.css': bad,
    });
    expect(scanConsumerCss(dir).findings).toEqual([]);
  });
});

describe('scanConsumerCss — detection', () => {
  it('flags system tokens redefined in every global scope', () => {
    const dir = mkProject({
      'src/a.css': [
        ':root { --color-accent: #ff3366; --spacing-4: 18px; }',
        'html { --font-size-base: 15px; }',
        ':host { --radius-element: 3px; }',
      ].join('\n'),
    });
    const f = scanConsumerCss(dir).findings;
    expect(kinds(f)).toEqual(Array(4).fill('root-token-override'));
    expect(f.map(x => x.detail)).toEqual([
      '--color-accent', '--spacing-4', '--font-size-base', '--radius-element',
    ]);
  });

  it('flags writes to private implementation vars', () => {
    const dir = mkProject({'src/a.css': '.x { --_button-radius: 2px; }'});
    const [f] = scanConsumerCss(dir).findings;
    expect(f.kind).toBe('private-var-write');
    expect(f.detail).toBe('--_button-radius');
  });

  it('flags deprecated bare prop classes', () => {
    const dir = mkProject({
      'src/a.css': '.astryx-button.primary { text-transform: uppercase; }',
    });
    const [f] = scanConsumerCss(dir).findings;
    expect(f.kind).toBe('deprecated-bare-class');
    expect(f.detail).toBe('.astryx-button.primary');
  });

  describe('replacement selector names the reflected prop key', () => {
    const replacementFor = async css => {
      const dir = mkProject({'src/a.css': css});
      const [f] = await resolveBareClasses(scanConsumerCss(dir).findings, CORE_SRC);
      return f?.replacement;
    };

    it('uses the prop key for an enumerated visual prop value', async () => {
      // Button.variant is 'primary' | 'secondary' | ...
      await expect(replacementFor('.astryx-button.primary { color: red; }')).resolves.toBe(
        '.astryx-button[data-variant="primary"]',
      );
    });

    it('uses the state name for a state, not data-variant', async () => {
      // Pagination renders themeProps('pagination-dot', {active: 'active'}),
      // so the reflection is [data-active="active"]. Hardcoding data-variant
      // produced a selector that matches nothing and silently drops the rule.
      await expect(
        replacementFor('.astryx-pagination-dot.active { background: red; }'),
      ).resolves.toBe('.astryx-pagination-dot[data-active="active"]');
    });

    it('distinguishes size from variant on a target that reflects both', async () => {
      await expect(replacementFor('.astryx-button.sm { padding: 2px; }')).resolves.toBe(
        '.astryx-button[data-size="sm"]',
      );
    });

    it('drops a token that is neither a state nor a documented prop value', async () => {
      const dir = mkProject({'src/a.css': '.astryx-button.totally-made-up { color: red; }'});
      const resolved = await resolveBareClasses(scanConsumerCss(dir).findings, CORE_SRC);
      expect(resolved).toEqual([]);
    });

    it('drops everything when the component docs cannot be resolved', async () => {
      // Naming an attribute without the docs would be a guess; flagging
      // without one would be noise.
      const dir = mkProject({'src/a.css': '.astryx-button.primary { color: red; }'});
      const resolved = await resolveBareClasses(scanConsumerCss(dir).findings, null);
      expect(resolved).toEqual([]);
    });
  });

  it('reports the line in the original file, not the comment-stripped one', () => {
    // Stripping comments outright collapses lines and shifts every finding.
    const dir = mkProject({
      'src/a.css': ['/*', ' * a', ' * long', ' * banner', ' */', '', '.x { --_r: 1px; }'].join('\n'),
    });
    expect(scanConsumerCss(dir).findings[0].line).toBe(7);
  });
});

describe('checkCssEscapes', () => {
  it('skips a project with no stylesheets', async () => {
    const c = await checkCssEscapes(ctx(mkProject({'package.json': '{}'})));
    expect(c.status).toBe('info');
  });

  it('passes clean CSS', async () => {
    const dir = mkProject({'src/a.css': '.x { color: var(--color-text-primary); }'});
    expect((await checkCssEscapes(ctx(dir))).status).toBe('pass');
  });

  it('fails on private vars — matching what `theme build` already rejects', async () => {
    const dir = mkProject({'src/a.css': '.x { --_card-radius: 0; }'});
    const c = await checkCssEscapes(ctx(dir));
    expect(c.status).toBe('fail');
    expect(c.fix).toMatch(/defineTheme/);
  });

  it('warns, not fails, on a global token override', async () => {
    const dir = mkProject({'src/a.css': ':root { --color-accent: #f00; }'});
    expect((await checkCssEscapes(ctx(dir))).status).toBe('warn');
  });

  it('stays silent on bare classes when the component docs are out of reach', async () => {
    // A throwaway project cannot resolve core, so nothing can be said about
    // which attribute replaces the class. Reporting it without a usable fix,
    // or guessing one, are both worse than saying nothing.
    const dir = mkProject({'src/a.css': '.astryx-badge.success { font-weight: 700; }'});
    expect((await checkCssEscapes(ctx(dir))).status).toBe('pass');
  });
});

describe('findSwizzled / checkSwizzled', () => {
  const swizzled = extra => ({
    'package.json': JSON.stringify({dependencies: {'@astryxdesign/core': '^0.3.0'}, ...extra}),
    'src/components/astryx/Button/Button.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Button() { return null; }",
    'src/components/astryx/Card/Card.tsx': 'export function Card() { return null; }',
  });

  it('finds swizzled component directories', () => {
    const {dirs, usesStyleX} = findSwizzled(mkProject(swizzled()));
    expect(dirs.map(d => path.basename(d)).sort()).toEqual(['Button', 'Card']);
    expect(usesStyleX).toBe(true);
  });

  it('fails when swizzled StyleX source has no compiler — it renders unstyled, silently', () => {
    const c = checkSwizzled(ctx(mkProject(swizzled())));
    expect(c.status).toBe('fail');
    expect(c.message).toMatch(/no StyleX compiler/i);
  });

  it('is only informational once a compiler is configured', () => {
    const dir = mkProject({
      ...swizzled({devDependencies: {'@stylexjs/babel-plugin': '^0.17.5'}}),
      'babel.config.js': "module.exports = {plugins: ['@stylexjs/babel-plugin']};",
    });
    expect(checkSwizzled(ctx(dir)).status).toBe('info');
  });

  it('WARNS when the plugin is installed but no build config references it', () => {
    // Declared is not configured. A plugin nothing invokes compiles nothing,
    // and the component renders unstyled exactly as if it were absent —
    // reporting `info` here was the false green.
    const dir = mkProject(swizzled({devDependencies: {'@stylexjs/babel-plugin': '^0.17.5'}}));
    const c = checkSwizzled(ctx(dir));
    expect(c.status).toBe('warn');
    expect(c.message).toMatch(/may never run/i);
  });

  it('passes a project with nothing swizzled', () => {
    const dir = mkProject({'package.json': '{}', 'src/App.tsx': 'export const A = 1;'});
    const c = checkSwizzled(ctx(dir));
    expect(c.status).toBe('pass');
    expect(c.fix).toBeUndefined();
  });

  it('does not mistake an unrelated directory named astryx for swizzle output', () => {
    // Only ./components/astryx/* is the swizzle target.
    const dir = mkProject({'package.json': '{}', 'src/astryx/helper.ts': 'export const x = 1;'});
    expect(findSwizzled(dir).dirs).toEqual([]);
  });

  // A monorepo is the normal case, and the compiler belongs to the app that
  // bundles the code. Reading only the ROOT package.json got both directions
  // wrong: it called an app with its own compiler broken, and would equally
  // have cleared an app that has none because a sibling did.
  //
  // Both plugins are wired the way a real config wires them — a called import
  // and a named entry — because a plugin that is merely imported and never
  // used compiles nothing, and no longer counts.
  const monorepo = (rootDeps, appDeps) => ({
    'package.json': JSON.stringify({private: true, ...rootDeps}),
    'apps/web/vite.config.js':
      "import stylex from 'vite-plugin-stylex';\n" +
      "export default {plugins: [stylex(), '@stylexjs/babel-plugin']};",
    'apps/web/package.json': JSON.stringify(appDeps ?? {}),
    'apps/web/src/components/astryx/Button/Button.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Button() { return null; }",
  });

  it('sees a compiler declared by the owning app, not just by the root', () => {
    const dir = mkProject(
      monorepo({}, {devDependencies: {'@stylexjs/babel-plugin': '^0.17.5'}}),
    );
    const c = checkSwizzled(ctx(dir));
    expect(c.status).toBe('info');
  });

  it('accepts a hoisted compiler declared at the workspace root', () => {
    const dir = mkProject(monorepo({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}, {}));
    expect(checkSwizzled(ctx(dir)).status).toBe('info');
  });

  it('fails the app that lacks a compiler even when a sibling has one', () => {
    const dir = mkProject({
      'package.json': '{"private": true}',
      'apps/wired/package.json': JSON.stringify({
        devDependencies: {'@stylexjs/babel-plugin': '^0.17.5'},
      }),
      'apps/wired/babel.config.js': "module.exports = {plugins: ['@stylexjs/babel-plugin']};",
      'apps/wired/src/components/astryx/Button/Button.tsx':
        "import * as stylex from '@stylexjs/stylex';\nexport function Button() { return null; }",
      'apps/bare/package.json': '{}',
      'apps/bare/src/components/astryx/Card/Card.tsx':
        "import * as stylex from '@stylexjs/stylex';\nexport function Card() { return null; }",
    });
    const c = checkSwizzled(ctx(dir));
    expect(c.status).toBe('fail');
    expect(c.message).toContain('apps/bare');
    expect(c.message).not.toContain('apps/wired');
    expect(c.fix).toContain('apps/bare');
  });

  it('reports per-package findings so a caller can act on the right one', () => {
    const dir = mkProject(
      monorepo({}, {devDependencies: {'@stylexjs/babel-plugin': '^0.17.5'}}),
    );
    const {packages} = findSwizzled(dir);
    expect(packages).toHaveLength(1);
    expect(path.basename(packages[0].dir)).toBe('web');
    expect(packages[0]).toMatchObject({usesStyleX: true, hasCompiler: true});
  });
});

describe('StyleX wiring — a comment is not configuration', () => {
  const swizzledStyleX = extra => ({
    'package.json': JSON.stringify({devDependencies: {'@stylexjs/babel-plugin': '^0.17.5'}}),
    'src/components/astryx/Button/Button.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Button() { return null; }",
    ...extra,
  });

  it('does not count a commented-out plugin as wiring', () => {
    // Reported a working setup for a project whose components render unstyled:
    // a bare includes() matched the plugin name inside a comment.
    const dir = mkProject(
      swizzledStyleX({'babel.config.js': "module.exports = {plugins: [/* '@stylexjs/babel-plugin' */]};"}),
    );
    expect(findSwizzled(dir).hasCompiler).toBeNull();
    expect(checkSwizzled(ctx(dir)).status).toBe('warn');
  });

  it('does not count the plugin named in prose', () => {
    const dir = mkProject(
      swizzledStyleX({'vite.config.js': '// TODO: evaluate @stylexjs/babel-plugin one day\nexport default {};'}),
    );
    expect(findSwizzled(dir).hasCompiler).toBeNull();
  });

  it('counts a real specifier', () => {
    const dir = mkProject(
      swizzledStyleX({'babel.config.js': "module.exports = {plugins: ['@stylexjs/babel-plugin']};"}),
    );
    expect(findSwizzled(dir).hasCompiler).toBe(true);
  });

  it('counts a real call', () => {
    const dir = mkProject(
      swizzledStyleX({
        'vite.config.js': "import stylex from 'vite-plugin-stylex';\nexport default {plugins: [stylex()]};",
        'package.json': JSON.stringify({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}),
      }),
    );
    expect(findSwizzled(dir).hasCompiler).toBe(true);
  });
});

describe('StyleX detection — one detector, so diagnosis and guidance cannot drift', () => {
  // doctor and the generated agent docs carried separate hardcoded plugin
  // lists. With @stylexjs/webpack-plugin configured, doctor called the swizzle
  // wired while the docs selected plain CSS — two answers about one project.
  const withPlugin = (plugin, config) => ({
    'package.json': JSON.stringify({devDependencies: {[plugin]: '^0.17.5'}}),
    'src/components/astryx/Button/Button.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Button() { return null; }",
    ...config,
  });

  it.each([
    ['@stylexjs/webpack-plugin', 'webpack.config.js', "const S = require('@stylexjs/webpack-plugin');\nmodule.exports = {plugins: [new S()]};"],
    ['@stylexjs/rollup-plugin', 'rollup.config.js', "import s from '@stylexjs/rollup-plugin';\nexport default {plugins: [s()]};"],
    ['@stylexjs/postcss-plugin', 'postcss.config.js', "module.exports = {plugins: ['@stylexjs/postcss-plugin']};"],
    ['@stylexjs/babel-plugin', 'babel.config.js', "module.exports = {plugins: ['@stylexjs/babel-plugin']};"],
  ])('%s: doctor and agent docs agree', (plugin, file, body) => {
    const dir = mkProject(withPlugin(plugin, {[file]: body}));
    expect(findSwizzled(dir).hasCompiler).toBe(true);
    expect(detectStylingSystem(dir)).toBe('stylex');
  });

  it('agree that a commented-out plugin is not wiring', () => {
    const dir = mkProject(
      withPlugin('@stylexjs/webpack-plugin', {
        'webpack.config.js': "module.exports = {plugins: [/* new StyleXPlugin() */]};",
      }),
    );
    expect(findSwizzled(dir).hasCompiler).toBeNull();
    expect(detectStylingSystem(dir)).toBe('css');
  });
});

describe('swizzle findings count and name only what is real', () => {
  it('counts the components that use StyleX, not every swizzled one', () => {
    // Reported "50 swizzled component(s) contain StyleX source" for a package
    // where exactly one did, because it counted the package's whole swizzle
    // list. The number is the reader's sense of scale — it has to be true.
    const files = {'package.json': '{"name":"a"}'};
    for (let i = 0; i < 12; i++) {
      files[`src/components/astryx/Plain${i}/Plain${i}.tsx`] = `export function Plain${i}() {}`;
    }
    files['src/components/astryx/Styled/Styled.tsx'] =
      "import * as stylex from '@stylexjs/stylex';\nexport function Styled() {}";
    const c = checkSwizzled(ctx(mkProject(files)));
    expect(c.status).toBe('fail');
    expect(c.message).toMatch(/^1 swizzled component\(s\)/);
    expect(c.message).toContain('Styled');
  });

  it('does not call a commented-out StyleX import "StyleX source"', () => {
    // That component compiles to plain React and renders fine; reporting it
    // sends people to install a compiler they do not need.
    const dir = mkProject({
      'package.json': '{"name":"a"}',
      'src/components/astryx/Y/Y.tsx':
        "// import * as stylex from '@stylexjs/stylex';\nexport function Y() {}",
    });
    expect(findSwizzled(dir).usesStyleX).toBe(false);
    expect(checkSwizzled(ctx(dir)).status).toBe('info');
  });

  it('does not count a plugin that is imported and never used', () => {
    // `import stylex from 'vite-plugin-stylex'` with `plugins: []` compiles
    // nothing — the components still render unstyled.
    const dir = mkProject({
      'package.json': JSON.stringify({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}),
      'vite.config.js': "import stylex from 'vite-plugin-stylex';\nexport default {plugins: []};",
      'src/components/astryx/Z/Z.tsx':
        "import * as stylex from '@stylexjs/stylex';\nexport function Z() {}",
    });
    expect(findSwizzled(dir).hasCompiler).toBeNull();
    expect(checkSwizzled(ctx(dir)).status).toBe('warn');
  });
});

describe('StyleX wiring must reach the bundler plugin list', () => {
  const app = cfg => ({
    'package.json': JSON.stringify({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}),
    'vite.config.js': cfg,
    'src/components/astryx/Z/Z.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Z() {}",
  });

  it('does not count a plugin that is called and discarded', () => {
    // `const unused = stylex()` beside `plugins: []` runs nowhere; the app
    // compiles no StyleX and its components render unstyled.
    const dir = mkProject(
      app("import s from 'vite-plugin-stylex';\nconst unused = s();\nexport default {plugins: []};"),
    );
    expect(findSwizzled(dir).hasCompiler).toBeNull();
  });

  it('counts a plugin called inside the plugin list', () => {
    const dir = mkProject(
      app("import s from 'vite-plugin-stylex';\nexport default {plugins: [s()]};"),
    );
    expect(findSwizzled(dir).hasCompiler).toBe(true);
  });

  it('counts a bare binding passed in the plugin list', () => {
    const dir = mkProject(app("import s from 'vite-plugin-stylex';\nexport default {plugins: [s]};"));
    expect(findSwizzled(dir).hasCompiler).toBe(true);
  });
});

describe('a quoted string is not a plugin list', () => {
  it('ignores "plugins: [...]" written inside a string', () => {
    const dir = mkProject({
      'package.json': JSON.stringify({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}),
      'vite.config.js': 'export default {doc: "plugins: [\'vite-plugin-stylex\']"};',
      'src/components/astryx/Z/Z.tsx':
        "import * as stylex from '@stylexjs/stylex';\nexport function Z() {}",
    });
    expect(findSwizzled(dir).hasCompiler).toBeNull();
  });
});

describe('only the EXPORTED config wires a compiler', () => {
  const app = cfg => ({
    'package.json': JSON.stringify({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}),
    'vite.config.js': cfg,
    'src/components/astryx/Z/Z.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Z() {}",
  });

  it('ignores plugins on an object the config never exports', () => {
    // Only the exported object reaches the bundler, so only it can answer.
    const dir = mkProject(
      app(
        "import s from 'vite-plugin-stylex';\n" +
          'const unused = {plugins: [s()]};\n' +
          'export default {plugins: []};',
      ),
    );
    expect(findSwizzled(dir).hasCompiler).toBeNull();
  });

  it('follows an export through an identifier', () => {
    const dir = mkProject(
      app("import s from 'vite-plugin-stylex';\nconst cfg = {plugins: [s()]};\nexport default cfg;"),
    );
    expect(findSwizzled(dir).hasCompiler).toBe(true);
  });

  it('follows an export through defineConfig()', () => {
    const dir = mkProject(
      app(
        "import {defineConfig} from 'vite';\nimport s from 'vite-plugin-stylex';\n" +
          'export default defineConfig({plugins: [s()]});',
      ),
    );
    expect(findSwizzled(dir).hasCompiler).toBe(true);
  });
});

describe('the config shapes real projects actually use', () => {
  const app = cfg => ({
    'package.json': JSON.stringify({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}),
    'vite.config.js': cfg,
    'src/components/astryx/Z/Z.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Z() {}",
  });
  const wired = cfg => findSwizzled(mkProject(app(cfg))).hasCompiler;

  // A config exported as a FUNCTION is standard Vite and Next. Reporting those
  // projects as unverified is a false alarm on a healthy setup, and a
  // diagnostic that cries wolf is one people learn to ignore.
  it.each([
    ['arrow returning a config', "export default () => ({plugins: [s()]});"],
    ['async arrow config', 'export default async () => ({plugins: [s()]});'],
    ['defineConfig(fn)', 'export default (({mode}) => ({plugins: [s()]}));'],
    ['block body with a return', 'export default () => { const p = [s()]; return {plugins: p}; };'],
    ['plugins bound to a const', 'const p = [s()];\nexport default {plugins: p};'],
    ['spread of a const array', 'const base = [s()];\nexport default {plugins: [...base]};'],
  ])('detects %s', (_label, body) => {
    expect(wired(`import s from 'vite-plugin-stylex';\n${body}`)).toBe(true);
  });

  it('a function config that does NOT wire it is still unverified', () => {
    expect(wired("import s from 'vite-plugin-stylex';\nexport default () => ({plugins: []});")).toBeNull();
  });

  it('an empty plugins const is still unverified', () => {
    expect(wired("import s from 'vite-plugin-stylex';\nconst p = [];\nexport default {plugins: p};")).toBeNull();
  });
});

describe('only a real bundler section counts', () => {
  const app = cfg => ({
    'package.json': JSON.stringify({devDependencies: {'vite-plugin-stylex': '^0.6.0'}}),
    'vite.config.js': cfg,
    'src/components/astryx/Z/Z.tsx':
      "import * as stylex from '@stylexjs/stylex';\nexport function Z() {}",
  });
  const wired = cfg => findSwizzled(mkProject(app(cfg))).hasCompiler;

  it('ignores a plugins key belonging to some other tool', () => {
    // Another tool's config living in the same file compiles nothing here.
    expect(
      wired(
        "import s from 'vite-plugin-stylex';\n" +
          'export default {someOtherTool: {plugins: [s()]}, plugins: []};',
      ),
    ).toBeNull();
  });

  it('accepts build.rollupOptions.plugins, which is genuine wiring', () => {
    expect(
      wired("import s from 'vite-plugin-stylex';\nexport default {build: {rollupOptions: {plugins: [s()]}}};"),
    ).toBe(true);
  });

  it('accepts css.postcss.plugins', () => {
    expect(
      wired("import s from 'vite-plugin-stylex';\nexport default {css: {postcss: {plugins: [s()]}}};"),
    ).toBe(true);
  });
});
