/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextInput — Optional and required
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextInput/TextInputOptionalAndRequired';
