/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DateInput — With Description And Required
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DateInput/DateInputWithDescriptionAndRequired';
