/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Collapsible — Standalone
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Collapsible/CollapsibleStandalone';
