// @generated by scripts/sync-api-types.mjs from the JSDoc in api/**/*.mjs.
// DO NOT EDIT — run `pnpm sync:api-types` to regenerate.

/**
 * @returns {Record<string, string>}
 */
export function discoverTopics(): Record<string, string>;
/**
 * @param {string} docPath
 * @param {{lang?: string|null}} [opts]
 * @returns {Promise<import('./docs.type.mjs').DocsDetailResponse['data']>}
 */
export function loadReferenceDocs(docPath: string, { lang }?: {
    lang?: string | null;
}): Promise<import("./docs.type.mjs").DocsDetailResponse["data"]>;
/**
 * Discover topics, resolve `topic` to its doc file (throwing `ERR_UNKNOWN_TOPIC`
 * when unmatched), and load that topic's reference doc with any --dense/--zh
 * overlay applied. Shared by the detail and section leaves so topic normalization
 * and unknown-topic handling live in exactly one place.
 *
 * @param {string} topic
 * @param {object} [options]
 * @param {string} [options.lang]
 * @param {boolean} [options.zh]
 * @param {boolean} [options.dense]
 * @returns {Promise<{
 *   topics: Record<string, string>,
 *   docsData: import('./docs.type.mjs').DocsDetailResponse['data'],
 * }>}
 */
export function resolveTopicDocs(topic: string, options?: {
    lang?: string | undefined;
    zh?: boolean | undefined;
    dense?: boolean | undefined;
}): Promise<{
    topics: Record<string, string>;
    docsData: import("./docs.type.mjs").DocsDetailResponse["data"];
}>;
