/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MobileNav — Basic Hamburger Menu
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MobileNav/MobileNavBasicHamburgerMenu';
