// @generated by scripts/gen-api-types.mjs from the JSDoc in api/**/*.mjs.
// DO NOT EDIT — run `pnpm gen:api-types` to regenerate.

/**
 * List posts from the feed.
 * @returns {Promise<import('../blog.type.mjs').BlogListResponse>}
 */
export function list(): Promise<import("../blog.type.mjs").BlogListResponse>;
