/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TreeList — With icons and header
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TreeList/TreeListWithIconsAndHeader';
