/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CommandPalette — Grouped Items
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CommandPalette/CommandPaletteGroupedItems';
