/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: SegmentedControl — Icon Only Compact
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/SegmentedControl/SegmentedControlIconOnlyCompact';
