/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: StatusDot — Pulsing animation
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/StatusDot/StatusDotPulsingAnimation';
