/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Field — With Description
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Field/FieldWithDescription';
