/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Toolbar — Card header pattern
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Toolbar/ToolbarCardHeaderPattern';
