/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: SideNav — Standalone (no TopNav)
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/SideNav/SideNavStandaloneNoTopNav';
