/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Typeahead — With validation status
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Typeahead/TypeaheadWithValidationStatus';
