/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Section — Transparent Variant
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Section/SectionTransparentVariant';
