/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AppShell — Controlled Collapse
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AppShell/AppShellControlledCollapse';
