/**
 * XDS Default Theme
 *
 * The reference theme — provides the standard XDS visual language.
 * Uses defineTheme for CSS-based theming (no StyleX build required for consumers).
 *
 * Typography sizing is driven by typography.scale, which auto-generates both
 * the token values (--text-heading-1-size, --text-body-size, etc.) and the
 * component override rules (.xds-heading.level-1 { font-size: ... }).
 *
 * Only non-typography component overrides need to be specified manually.
 */

import {defineTheme} from '@xds/core/theme';
import {defaultIconRegistry} from './icons';

export const defaultTheme = defineTheme({
  name: 'default',

  // Typography: base=14px, ratio=1.2, h4 anchored to base.
  // Generates all heading + text tokens AND component overrides automatically.
  typography: {scale: {base: 14, ratio: 1.2}},

  // Motion: base durations from Ted's proposal (#674), ratio=0.75.
  // Generates: fast-min=130ms, fast=175ms, fast-max=235ms,
  //            medium-min=310ms, medium=410ms, medium-max=545ms.
  motion: {fast: 175, medium: 410, ratio: 0.75},

  // The default theme uses the built-in token defaults from tokens.stylex.ts.
  // Syntax highlighting tokens tuned to the default palette.
  tokens: {
    '--color-syntax-keyword': 'light-dark(#0064E0, #2694FE)',
    '--color-syntax-string': 'light-dark(#09441F, #A5F690)',
    '--color-syntax-comment': 'light-dark(#4E606F, #6B7D8D)',
    '--color-syntax-number': 'light-dark(#6B2203, #FDB876)',
    '--color-syntax-function': 'light-dark(#042F97, #AFD7FF)',
    '--color-syntax-type': 'light-dark(#3E0697, #B3B0FE)',
    '--color-syntax-variable': 'light-dark(#0A1317, #DFE2E5)',
    '--color-syntax-operator': 'light-dark(#006D75, #56C8D8)',
    '--color-syntax-constant': 'light-dark(#6B2203, #FDB876)',
    '--color-syntax-tag': 'light-dark(#7B0210, #FFB2B8)',
    '--color-syntax-attribute': 'light-dark(#7A4F1A, #E8C580)',
    '--color-syntax-property': 'light-dark(#006064, #B2EBF2)',
    '--color-syntax-punctuation': 'light-dark(#65737E, #6F747C)',
    '--color-syntax-background': 'light-dark(#F1F4F7, #111112)',
  },

  components: {
    // =========================================================================
    // Button
    // =========================================================================
    button: {
      'variant:secondary': {
        backgroundColor:
          'light-dark(rgba(5, 54, 89, 0.1), rgba(223, 226, 229, 0.2))',
      },
    },

    // Heading and text component overrides are auto-generated by typography.scale.
    // No manual heading: { ... } or text: { ... } blocks needed.
  },

  // =========================================================================
  // On-media overrides
  // =========================================================================
  // Customize how components look on inverted surfaces (e.g. dark toast on
  // a light page). color-scheme + base token overrides are provided by
  // default; these add component-level adjustments.

  onDark: {
    components: {
      button: {
        'variant:secondary': {
          backgroundColor: 'color-mix(in srgb, white 20%, transparent)',
        },
      },
    },
  },

  onLight: {
    components: {
      button: {
        'variant:secondary': {
          backgroundColor: 'color-mix(in srgb, black 10%, transparent)',
        },
      },
    },
  },

  icons: defaultIconRegistry,
});
