/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: IconButton — Emoji
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/IconButton/IconButtonEmoji';
