/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CheckboxInput — Indeterminate
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CheckboxInput/CheckboxInputIndeterminate';
