/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Text — Font wrapper for native HTML
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Text/TextFontWrapperForNativeHTML';
