/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Banner — With Content
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Banner/BannerWithContent';
