/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MobileNav — Shared Children With SideNav
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MobileNav/MobileNavSharedChildrenWithSideNav';
