/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: EmptyState — Full Example
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/EmptyState/EmptyStateFullExample';
