/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: FormLayout — Dialog Composition
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/FormLayout/FormLayoutDialogComposition';
