/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MetadataList — Multi Column
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MetadataList/MetadataListMultiColumn';
