/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Calendar — Two Months
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Calendar/CalendarTwoMonths';
