/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Token — Clickable
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Token/TokenClickable';
