/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Button — Basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Button/ButtonBasic';
