/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ProgressBar — Composed With External Description
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ProgressBar/ProgressBarComposedWithExternalDescription';
