/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TimeInput — Async action with optimistic update
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TimeInput/TimeInputAsyncActionWithOptimisticUpdate';
