/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TimeInput — With seconds and error status
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TimeInput/TimeInputWithSecondsAndErrorStatus';
