/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AlertDialog — Delete Confirmation
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AlertDialog/AlertDialogDeleteConfirmation';
