/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DropdownMenu — Basic Usage
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DropdownMenu/DropdownMenuBasicUsage';
