/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Toolbar — Three-slot layout with centered content
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Toolbar/ToolbarThreeslotLayoutWithCenteredContent';
