/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CheckboxInput — Async Action
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CheckboxInput/CheckboxInputAsyncAction';
