/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: PowerSearch — With Initial Filters
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/PowerSearch/PowerSearchWithInitialFilters';
