/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Text — Truncated text with tooltip
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Text/TextTruncatedTextWithTooltip';
