/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Grid — Spanning Columns
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Grid/GridSpanningColumns';
