/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextInput — Async action with loading state
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextInput/TextInputAsyncActionWithLoadingState';
