/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Timestamp — Time only
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Timestamp/TimestampTimeOnly';
