/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Timestamp — Relative format
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Timestamp/TimestampRelativeFormat';
