// @generated by scripts/sync-api-types.mjs from the JSDoc in api/**/*.mjs.
// DO NOT EDIT — run `pnpm sync:api-types` to regenerate.

/**
 * @param {string} topic
 * @param {object} [options]
 * @param {string} [options.lang]
 * @param {boolean} [options.zh]
 * @param {boolean} [options.dense]
 * @returns {Promise<import('../docs.type.mjs').DocsDetailResponse>}
 */
export function detail(topic: string, options?: {
    lang?: string | undefined;
    zh?: boolean | undefined;
    dense?: boolean | undefined;
}): Promise<import("../docs.type.mjs").DocsDetailResponse>;
