/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Table — Column alignment and vertical alignment
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Table/TableColumnAlignmentAndVerticalAlignment';
