/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: NumberInput — Optional Field
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/NumberInput/NumberInputOptionalField';
