/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: OverflowList — Overflow Into Dropdown Menu
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/OverflowList/OverflowListOverflowIntoDropdownMenu';
