/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Tooltip — useXDSTooltip hook
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Tooltip/TooltipUseXDSTooltipHook';
