// @generated by scripts/gen-api-types.mjs from the JSDoc in api/**/*.mjs.
// DO NOT EDIT — run `pnpm gen:api-types` to regenerate.

/**
 * @returns {Promise<import('../docs.type.mjs').DocsListResponse>}
 */
export function list(): Promise<import("../docs.type.mjs").DocsListResponse>;
