/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Spinner — Default
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Spinner/SpinnerDefault';
