// @generated by scripts/gen-api-types.mjs from the JSDoc in api/**/*.mjs.
// DO NOT EDIT — run `pnpm gen:api-types` to regenerate.

/**
 * Build the `template.show` envelope for an already-resolved template.
 * @param {import('../_adapter.mjs').DiscoveredTemplate} match
 * @returns {import('../template.type.mjs').TemplateShowResponse}
 */
export function templateShow(match: import("../_adapter.mjs").DiscoveredTemplate): import("../template.type.mjs").TemplateShowResponse;
