// Copyright (c) Meta Platforms, Inc. and affiliates.

import {mkdir, readdir, readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const repoRoot = path.resolve(packageRoot, '../..');
const tokenSourcePath = path.join(
  repoRoot,
  'packages/core/src/theme/tokens.stylex.ts',
);
const baseCSSPath = path.join(packageRoot, 'src/base.css');
const componentsDir = path.join(packageRoot, 'src/components');
const sourceJSPath = path.join(packageRoot, 'src/js/index.js');
const distDir = path.join(packageRoot, 'dist');
const distCSSPath = path.join(distDir, 'astryx-vanilla.css');
const distJSPath = path.join(distDir, 'astryx-vanilla.js');
const distMJSPath = path.join(distDir, 'astryx-vanilla.mjs');

export function extractTokenDefaults(source) {
  const tokens = new Map();
  const familyPattern =
    /export const [A-Za-z]+Defaults = (\{[\s\S]*?\n\}) as const;/g;

  for (const match of source.matchAll(familyPattern)) {
    // The canonical *Defaults objects contain string values and JavaScript
    // comments only. Evaluating the isolated object literal keeps this build
    // dependency-free while deriving every declaration from the source of truth.
    const family = Function(`"use strict"; return (${match[1]});`)();
    for (const [name, value] of Object.entries(family)) {
      if (!name.startsWith('--') || typeof value !== 'string') {
        throw new Error(`Unsupported token default ${name}`);
      }
      if (tokens.has(name)) {
        throw new Error(`Duplicate token default ${name}`);
      }
      tokens.set(name, value);
    }
  }

  if (tokens.size === 0) {
    throw new Error(`No token defaults found in ${tokenSourcePath}`);
  }

  return tokens;
}

function indent(content, spaces) {
  const prefix = ' '.repeat(spaces);
  return content
    .trim()
    .split('\n')
    .map(line => (line ? `${prefix}${line}` : ''))
    .join('\n');
}

export function renderCSS(baseCSS, components, tokens) {
  const declarations = [...tokens]
    .map(([name, value]) => `    ${name}: ${value};`)
    .join('\n');
  const componentCSS = components
    .map(({name, content}) => `  /* ${name} */\n${indent(content, 2)}`)
    .join('\n\n');

  return `/* Generated by packages/vanilla/scripts/build.mjs from core token defaults and component CSS. */
@layer reset, astryx-base, astryx-prose, astryx-theme;

@layer astryx-base {
  /* Generated token defaults. Shipped themes override these in astryx-theme. */
  :root {
${declarations}
  }

${indent(baseCSS, 2)}

${componentCSS}
}
`;
}

export function renderClassicJS(source) {
  const body = source
    .replace(/^\/\/ Copyright[^\n]*\n+/, '')
    .replace(/\nexport \{[^}]+\};\s*$/, '');

  return `/* Copyright (c) Meta Platforms, Inc. and affiliates. */

(() => {
  'use strict';

${indent(body, 2)}

  globalThis.AstryxVanilla = Object.freeze({
    initThemeModeSwitchers,
    setMode,
    setTheme,
  });
})();
`;
}

async function readComponentCSS() {
  const entries = await readdir(componentsDir, {withFileTypes: true});
  const files = entries
    .filter(entry => entry.isFile() && entry.name.endsWith('.css'))
    .map(entry => entry.name)
    .sort((a, b) => a.localeCompare(b));

  if (files.length === 0) {
    throw new Error(`No component CSS found in ${componentsDir}`);
  }

  return Promise.all(
    files.map(async file => ({
      name: path.basename(file, '.css'),
      content: await readFile(path.join(componentsDir, file), 'utf8'),
    })),
  );
}

async function build() {
  const [tokenSource, baseCSS, components, sourceJS] = await Promise.all([
    readFile(tokenSourcePath, 'utf8'),
    readFile(baseCSSPath, 'utf8'),
    readComponentCSS(),
    readFile(sourceJSPath, 'utf8'),
  ]);
  const tokens = extractTokenDefaults(tokenSource);
  const generatedCSS = renderCSS(baseCSS, components, tokens);
  const generatedClassicJS = renderClassicJS(sourceJS);

  if (process.argv.includes('--check')) {
    const [currentCSS, currentJS, currentMJS] = await Promise.all([
      readFile(distCSSPath, 'utf8'),
      readFile(distJSPath, 'utf8'),
      readFile(distMJSPath, 'utf8'),
    ]);
    if (
      currentCSS !== generatedCSS ||
      currentJS !== generatedClassicJS ||
      currentMJS !== sourceJS
    ) {
      throw new Error(
        'Committed dist is stale; run pnpm -F @astryxdesign/vanilla build',
      );
    }
    console.log('Vanilla dist is current.');
    return;
  }

  await mkdir(distDir, {recursive: true});
  await Promise.all([
    writeFile(distCSSPath, generatedCSS),
    writeFile(distJSPath, generatedClassicJS),
    writeFile(distMJSPath, sourceJS),
  ]);
  console.log(
    `Generated ${path.relative(repoRoot, distCSSPath)} (${tokens.size} tokens, ${components.length} components)`,
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  build().catch(error => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
