/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Table — Rich cell content with renderCell
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Table/TableRichCellContentWithRenderCell';
