/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CheckboxList — Standalone Mode
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CheckboxList/CheckboxListStandaloneMode';
