/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Layout — Card Layout
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Layout/LayoutCardLayout';
