/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Breadcrumbs — Item With Icon
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Breadcrumbs/BreadcrumbsItemWithIcon';
