/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Timestamp — Auto format (default)
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Timestamp/TimestampAutoFormatDefault';
