/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AppShell — Padded Content
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AppShell/AppShellPaddedContent';
