/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Breadcrumbs — Supporting Variant
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Breadcrumbs/BreadcrumbsSupportingVariant';
