/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TopNav — With centered content (three-column layout)
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TopNav/TopNavWithCenteredContentThreecolumnLayout';
