/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Card — Basic With Layout
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Card/CardBasicWithLayout';
