/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Text — Supporting text
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Text/TextSupportingText';
