/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Field — Required
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Field/FieldRequired';
