/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Calendar — Range Selection
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Calendar/CalendarRangeSelection';
