/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Card — Collapsible
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Card/CardCollapsible';
