/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TimeInput — 24-hour format with clear button
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TimeInput/TimeInput24hourFormatWithClearButton';
