// @generated by scripts/gen-api-types.mjs from the JSDoc in api/**/*.mjs.
// DO NOT EDIT — run `pnpm gen:api-types` to regenerate.

/**
 * List swizzlable components discoverable from `cwd`'s @astryxdesign/core.
 * @param {string} [cwd]
 * @returns {import('../swizzle.type.mjs').SwizzleListResponse}
 */
export function swizzleList(cwd?: string): import("../swizzle.type.mjs").SwizzleListResponse;
