/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: OverflowList — Basic With Overflow Button
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/OverflowList/OverflowListBasicWithOverflowButton';
