/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DropdownMenu — Custom Item Rendering
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DropdownMenu/DropdownMenuCustomItemRendering';
