/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Pagination — Cursor Based
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Pagination/PaginationCursorBased';
