/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Tokenizer — With max entries and clear all
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Tokenizer/TokenizerWithMaxEntriesAndClearAll';
