/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Tokenizer — Custom token rendering
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Tokenizer/TokenizerCustomTokenRendering';
