/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: MetadataList — Horizontal
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/MetadataList/MetadataListHorizontal';
