/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Spinner — With label
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Spinner/SpinnerWithLabel';
