/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: ProgressBar — Determinate
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/ProgressBar/ProgressBarDeterminate';
