/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Token — Removable
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Token/TokenRemovable';
