/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Popover — Basic
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Popover/PopoverBasic';
