"use client";

/**
 * StyleX Theme Prototype v2 — CSS Variable Bindings
 *
 * Strategy:
 * 1. Build generates a CSS var per themeable property
 * 2. Build generates a "binding class" that reads it via var()
 * 3. Theme scopes set the var value
 * 4. Component includes binding classes via $$css in stylex.props
 * 5. Product override strips the binding class via styleq → var gone
 *
 * No @scope. No layers. Just vars + styleq dedup.
 */

import React from "react";
import * as stylex from "@stylexjs/stylex";
import "./themes.css";

// =============================================================================
// THEME BINDINGS (generated by build — static, same regardless of theme)
// Each property maps to a "binding class" that applies var(--xds-...).
// When styleq strips the binding class, the var() disappears entirely.
// =============================================================================

const themeBindings = {
  button: {
    root: {
      $$css: true,
      borderRadius: "xds-bind-btn-borderRadius",
      textTransform: "xds-bind-btn-textTransform",
      letterSpacing: "xds-bind-btn-letterSpacing",
      fontWeight: "xds-bind-btn-fontWeight",
    } as Record<string, string | boolean> & { $$css: true },
  },
};

// =============================================================================
// PROTOTYPE BUTTON
// =============================================================================

const baseStyles = stylex.create({
  root: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 16px",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    backgroundColor: "#e4e4e7",
    color: "#18181b",
    fontFamily: "system-ui, sans-serif",
  },
});

const productOverrides = stylex.create({
  customRadius: {
    borderRadius: "20px",
  },
  customWeight: {
    fontWeight: "300",
  },
});

function DemoButton({
  label,
  xstyle,
}: {
  label: string;
  xstyle?: stylex.StyleXStyles;
}) {
  return (
    <button
      {...stylex.props(
        baseStyles.root,
        themeBindings.button.root as unknown as stylex.StyleXStyles,
        xstyle
      )}
    >
      {label}
    </button>
  );
}

// =============================================================================
// PAGE STYLES
// =============================================================================

const s = stylex.create({
  page: {
    padding: "32px",
    fontFamily: "system-ui, sans-serif",
    maxWidth: "800px",
    margin: "0 auto",
  },
  section: {
    marginBottom: "24px",
    padding: "24px",
    borderRadius: "8px",
    border: "1px solid #e4e4e7",
  },
  title: {
    fontSize: "14px",
    fontWeight: "600",
    marginBottom: "8px",
  },
  desc: {
    fontSize: "13px",
    color: "#71717a",
    marginBottom: "16px",
    lineHeight: "1.5",
  },
  row: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  nested: {
    padding: "16px",
    borderRadius: "6px",
    border: "1px dashed #a1a1aa",
    marginTop: "12px",
  },
  label: {
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: "#a1a1aa",
    marginBottom: "8px",
    fontWeight: "600",
  },
  h1: {
    fontSize: "24px",
    fontWeight: "700",
    marginBottom: "4px",
  },
  subtitle: {
    fontSize: "14px",
    color: "#71717a",
    marginBottom: "32px",
  },
  howItWorks: {
    fontSize: "13px",
    color: "#52525b",
    lineHeight: "1.8",
  },
  codeBlock: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "12px",
    backgroundColor: "#f4f4f5",
    padding: "12px 16px",
    borderRadius: "6px",
    whiteSpace: "pre",
    overflow: "auto",
    marginTop: "8px",
    lineHeight: "1.6",
  },
});

// =============================================================================
// TEST PAGE
// =============================================================================

export default function StyleXThemeTestPage() {
  return (
    <div {...stylex.props(s.page)}>
      <h1 {...stylex.props(s.h1)}>StyleX Theme v2: CSS Variable Bindings</h1>
      <p {...stylex.props(s.subtitle)}>
        base &lt; theme (var inheritance) &lt; override (stylex merge)
      </p>

      {/* Test 1: Theme overrides base */}
      <div {...stylex.props(s.section)}>
        <div {...stylex.props(s.title)}>Test 1: Theme overrides base</div>
        <p {...stylex.props(s.desc)}>
          Base: border-radius 6px, font-weight 500. Inside brutalist scope,
          binding class applies var(--xds-button-root-borderRadius) which
          resolves to 9999px.
        </p>
        <div data-xds-theme="brutalist">
          <div {...stylex.props(s.label)}>scope: brutalist</div>
          <div {...stylex.props(s.row)}>
            <DemoButton label="Brutalist Button" />
          </div>
        </div>
      </div>

      {/* Test 2: Nested themes */}
      <div {...stylex.props(s.section)}>
        <div {...stylex.props(s.title)}>
          Test 2: Nested themes — inner scope wins
        </div>
        <p {...stylex.props(s.desc)}>
          CSS custom properties inherit. Inner [data-xds-theme=&quot;neutral&quot;]
          resets --xds-button-root-borderRadius to 8px, overriding outer
          brutalist via standard CSS custom property inheritance.
        </p>
        <div data-xds-theme="brutalist">
          <div {...stylex.props(s.label)}>outer: brutalist</div>
          <div {...stylex.props(s.row)}>
            <DemoButton label="Outer (brutalist)" />
          </div>
          <div data-xds-theme="neutral" {...stylex.props(s.nested)}>
            <div {...stylex.props(s.label)}>inner: neutral</div>
            <div {...stylex.props(s.row)}>
              <DemoButton label="Inner (neutral)" />
            </div>
          </div>
        </div>
      </div>

      {/* Test 3: Product override beats theme */}
      <div {...stylex.props(s.section)}>
        <div {...stylex.props(s.title)}>
          Test 3: Product override beats theme
        </div>
        <p {...stylex.props(s.desc)}>
          xstyle sets borderRadius: 20px. styleq strips the binding class
          for borderRadius — the var() reference disappears. Hardcoded wins.
        </p>
        <div data-xds-theme="brutalist">
          <div {...stylex.props(s.label)}>brutalist + xstyle override</div>
          <div {...stylex.props(s.row)}>
            <DemoButton label="No override" />
            <DemoButton
              label="xstyle: borderRadius 20px"
              xstyle={productOverrides.customRadius}
            />
          </div>
        </div>
      </div>

      {/* Test 4: Partial override */}
      <div {...stylex.props(s.section)}>
        <div {...stylex.props(s.title)}>
          Test 4: Partial override — only strips overridden property
        </div>
        <p {...stylex.props(s.desc)}>
          Override sets fontWeight: 300 only. borderRadius binding stays
          (still reads var → 9999px from brutalist). Only fontWeight binding
          stripped.
        </p>
        <div data-xds-theme="brutalist">
          <div {...stylex.props(s.label)}>
            brutalist + partial xstyle (fontWeight only)
          </div>
          <div {...stylex.props(s.row)}>
            <DemoButton label="No override" />
            <DemoButton
              label="fontWeight: 300 (radius stays 9999px)"
              xstyle={productOverrides.customWeight}
            />
          </div>
        </div>
      </div>

      {/* Test 5: No theme scope */}
      <div {...stylex.props(s.section)}>
        <div {...stylex.props(s.title)}>
          Test 5: No theme scope — vars unset, base wins
        </div>
        <p {...stylex.props(s.desc)}>
          Outside any theme scope, vars are undefined. Binding classes produce
          invalid values, browser ignores them, and base StyleX classes
          (earlier in the className) provide the fallback.
        </p>
        <div>
          <div {...stylex.props(s.label)}>no theme scope</div>
          <div {...stylex.props(s.row)}>
            <DemoButton label="Should show base (6px radius)" />
          </div>
        </div>
      </div>

      {/* Architecture */}
      <div {...stylex.props(s.section)}>
        <div {...stylex.props(s.title)}>Architecture</div>
        <div {...stylex.props(s.codeBlock)}>
{`Theme config
  → build
  → CSS: [data-xds-theme="X"] { --xds-button-root-borderRadius: 9999px }
  → CSS: .xds-bind-btn-borderRadius { border-radius: var(--xds-...) }
  → JS:  themeBindings.button.root = { $$css: true, borderRadius: "xds-bind-..." }

Component render:
  stylex.props(styles.root, themeBindings.button.root, xstyle)

Resolution:
  base       → styles.root compiled class (border-radius: 6px)
  theme      → binding class wins (same specificity, later in className)
               reads var() → value from nearest ancestor scope
  override   → xstyle strips binding class via styleq → var() gone
  no theme   → var() unresolved → browser ignores → base class applies`}
        </div>
      </div>
    </div>
  );
}
