/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: TextInput — Validation status
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/TextInput/TextInputValidationStatus';
