/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: DropdownMenu — Controlled Mode
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/DropdownMenu/DropdownMenuControlledMode';
