/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Switch — With description
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Switch/SwitchWithDescription';
