/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: RadioList — Disabled Group
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/RadioList/RadioListDisabledGroup';
