/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Field — Basic Usage
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Field/FieldBasicUsage';
