/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: CodeBlock — TypeScript With Line Numbers
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/CodeBlock/CodeBlockTypeScriptWithLineNumbers';
