/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Table — Basic data-driven table
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Table/TableBasicDatadrivenTable';
