/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Tokenizer — Basic multi-select
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Tokenizer/TokenizerBasicMultiselect';
