/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Skeleton — Staggered animation for multiple skeletons
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Skeleton/SkeletonStaggeredAnimationForMultipleSkeletons';
