/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: AppShell — Auto Height
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/AppShell/AppShellAutoHeight';
