/**
 * AUTO-GENERATED by scripts/sync-templates.js — do not edit.
 * Block: Section — Full Bleed
 */
export {default} from '../../../../../../../packages/cli/templates/blocks/components/Section/SectionFullBleed';
